package:
  name: atlantis
  version: 0.26.0
  epoch: 2
  description: Terraform Pull Request Automation
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - wolfi-baselayout
      - ca-certificates-bundle
      - busybox
      - go
      - build-base
      - libcap-utils

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/runatlantis/atlantis
      tag: v${{package.version}}
      expected-commit: bb18da218ddb8af5cff7f0b19c32869cc0b3b84d

  - uses: go/build
    with:
      modroot: .
      packages: .
      output: atlantis
      ldflags: -w -X main.version=${{package.version}} -X main.commit=$(git rev-parse HEAD) -X main.date=$(date ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")

  - uses: strip

  # This must come after strip!
  - runs: |
      setcap "cap_net_bind_service=+ep" "${{targets.destdir}}"/usr/bin/atlantis

update:
  enabled: true
  github:
    identifier: runatlantis/atlantis
    strip-prefix: v
    use-tag: true
