package:
  name: aws-ebs-csi-driver
  version: 1.24.0
  epoch: 0
  description: CSI driver for Amazon EBS.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - mount
      - lsblk
      - blkid
      - blockdev
      - xfsprogs
      - e2fsprogs
      - e2fsprogs-extra

environment:
  contents:
    packages:
      - wolfi-baselayout
      - busybox
      - build-base
      - go
      - ca-certificates-bundle

pipeline:
  # We can't use go/install because this requires specific ldflags to set the version
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/aws-ebs-csi-driver
      tag: v${{package.version}}
      expected-commit: 8096deb12cfa7a101db79b8c3bffd08434fc5676

  - runs: |
      # CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy

      # Our global LDFLAGS conflict with a Makefile parameter
      unset LDFLAGS
      make ARCH=$(go env GOARCH)
      mkdir -p ${{targets.destdir}}/usr/bin
      cp bin/aws-ebs-csi-driver ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/aws-ebs-csi-driver
    strip-prefix: v
    use-tag: true
    tag-filter: v
