package:
  name: boring-registry
  version: 0.11.4
  epoch: 4
  description: Terraform Provider and Module Registry
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/TierMobility/boring-registry
      expected-commit: 083aa721311a3745ee0e5bd3b68bfce7ed2c1f4c
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: .
      output: boring-registry
      ldflags: |
        -s -w
        -X github.com/TierMobility/boring-registry/version.Version="${{package.version}}"
        -X github.com/TierMobility/boring-registry/version.Commit="$(git rev-parse --verify HEAD --short)"
        -X github.com/TierMobility/boring-registry/version.Date="$(date -u +'%FT%T%z')"
      # CVE-2023-39325 and CVE-2023-3978
      deps: golang.org/x/net@v0.17.0
      vendor: "true"

  - uses: strip

update:
  enabled: true
  github:
    identifier: TierMobility/boring-registry
    strip-prefix: v
