package:
  name: cadvisor
  version: 0.47.3
  epoch: 5
  description: Analyzes resource usage and performance characteristics of running containers.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - bash
      - build-base
      - go-1.20 # Pinned to 1.20 due to upstream issues with 1.21

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/google/cadvisor
      tag: v${{package.version}}
      expected-commit: c5730c5a72b527a724e7333d0e2f5b9a3ce5cf4d

  - runs: |
      # Handle CVE-2022-41723 CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      # Handle CVE-2023-27561
      go get github.com/opencontainers/runc@v1.1.5
      # Handle GHSA-232p-vwff-86mp GHSA-33pg-m6jh-5237 and GHSA-6wrf-mxfj-pf5p
      go get github.com/docker/docker@v20.10.24
      # Handle GHSA-hqxw-f8mx-cpmw
      go get github.com/docker/distribution@v2.8.2
      go mod tidy
      cd cmd
      # Handle CVE-2022-41723 CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy
      cd ..
      ./build/build.sh

  - runs: |
      install -Dm755 _output/cadvisor "${{targets.destdir}}"/usr/bin/cadvisor

  - uses: strip

update:
  enabled: true
  github:
    identifier: google/cadvisor
    strip-prefix: v
    tag-filter: v
    use-tag: true
