package:
  name: cert-manager-1.12
  # See https://cert-manager.io/docs/installation/supported-releases/ for upstream-supported versions
  version: 1.12.5
  epoch: 3
  description: Automatically provision and manage TLS certificates in Kubernetes
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - cert-manager=1.12.999 # This is because we had a 1.12.3 cert-manager package, remove in 1.13+

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go
      - make
      - curl
      - jq

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cert-manager/cert-manager
      tag: v${{package.version}}
      expected-commit: a7ea746ceb7f2180597a1ed13df7ef7e5fdbc745

  # the makefile hardcodes the requirement for some container runtime (CTR), even when we don't need it
  # to workaround, set CTR to anything $(command -v)able
  - runs: |
      for mod in controller webhook cainjector acmesolver; do
        cd cmd/$mod
        # CVE-2023-39325 and CVE-2023-3978
        go get golang.org/x/net@v0.17.0
        go mod tidy
        cd ../..
      done

      make CTR=make _bin/server/controller-linux-$(go env GOARCH)
      make CTR=make _bin/server/webhook-linux-$(go env GOARCH)
      make CTR=make _bin/server/cainjector-linux-$(go env GOARCH)
      make CTR=make _bin/server/acmesolver-linux-$(go env GOARCH)

      mkdir -p ${{targets.destdir}}/usr/bin
      mv _bin/server/* ${{targets.destdir}}/usr/bin/

  - uses: strip

subpackages:
  - name: ${{package.name}}-controller
    pipeline:
      - runs: |
          install -Dm755 ${{targets.destdir}}/usr/bin/controller-linux-$(go env GOARCH) ${{targets.subpkgdir}}/usr/bin/controller
    dependencies:
      provides:
        - cert-manager-controller=1.12.999 # This is because we had a 1.12.3 cert-manager package, remove in 1.13+

  - name: ${{package.name}}-webhook
    pipeline:
      - runs: |
          install -Dm755 ${{targets.destdir}}/usr/bin/webhook-linux-$(go env GOARCH) ${{targets.subpkgdir}}/usr/bin/webhook
    dependencies:
      provides:
        - cert-manager-webhook=1.12.999 # This is because we had a 1.12.3 cert-manager package, remove in 1.13+

  - name: ${{package.name}}-cainjector
    pipeline:
      - runs: |
          install -Dm755 ${{targets.destdir}}/usr/bin/cainjector-linux-$(go env GOARCH) ${{targets.subpkgdir}}/usr/bin/cainjector
    dependencies:
      provides:
        - cert-manager-cainjector=1.12.999 # This is because we had a 1.12.3 cert-manager package, remove in 1.13+

  - name: ${{package.name}}-acmesolver
    pipeline:
      - runs: |
          install -Dm755 ${{targets.destdir}}/usr/bin/acmesolver-linux-$(go env GOARCH) ${{targets.subpkgdir}}/usr/bin/acmesolver
    dependencies:
      provides:
        - cert-manager-acmesolver=1.12.999 # This is because we had a 1.12.3 cert-manager package, remove in 1.13+

  - name: cmctl-1.12
    pipeline:
      - runs: |
          make CTR=make cmctl-linux
      - runs: |
          install -Dm755 _bin/cmctl/cmctl-linux-$(go env GOARCH) ${{targets.subpkgdir}}/usr/bin/cmctl
      - uses: strip
    dependencies:
      provides:
        - cmctl=1.12.999 # This is because we had a 1.12.3 cert-manager package, remove in 1.13+

update:
  enabled: true
  github:
    identifier: cert-manager/cert-manager
    strip-prefix: v
    tag-filter: v1.12.
    use-tag: true
