package:
  name: chartmuseum
  version: 0.16.0
  epoch: 6
  description: helm chart repository server
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - bash
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/helm/chartmuseum
      tag: v${{package.version}}
      expected-commit: 31cd02b074a1beb6c85cdb657e0b1fdb1e78970b
      destination: chartmuseum

  - runs: |
      cd chartmuseum
      # Handle CVE-2022-41723 CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy

      CGO_ENABLED=0 go build --ldflags="-s -w -X main.Version=${{package.version}} \
        -X main.Revision=$(git rev-parse --short HEAD)" \
        -o "${{targets.destdir}}/usr/bin/chartmuseum" \
        cmd/chartmuseum/main.go

  - uses: strip

update:
  enabled: true
  github:
    identifier: helm/chartmuseum
    strip-prefix: v
