package:
  name: cluster-autoscaler-1.28
  version: 1.28.0
  epoch: 5
  description: Autoscaling components for Kubernetes
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - cluster-autoscaler=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - go
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes/autoscaler
      tag: cluster-autoscaler-${{package.version}}
      expected-commit: 5bcb526e08c17ff93cc6093ee89a95730a90e45b

  - uses: go/build
    with:
      modroot: cluster-autoscaler
      packages: .
      output: cluster-autoscaler
      ldflags: -s -w
      # CVE-2023-39325 and CVE-2023-3978
      deps: github.com/docker/distribution@v2.8.2 golang.org/x/net@v0.17.0
      vendor: true

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}
          # The upstream helm chart assumes the binary is in /.
          ln -sf /usr/bin/cluster-autoscaler ${{targets.subpkgdir}}/cluster-autoscaler
    dependencies:
      provides:
        - cluster-autoscaler-compat=${{package.full-version}}

update:
  enabled: true
  github:
    identifier: kubernetes/autoscaler
    strip-prefix: cluster-autoscaler-
    use-tag: true
    # There are other tags like "cluster-autoscaler-chart-FOO"
    tag-filter: cluster-autoscaler-1.28.
