package:
  name: conda
  version: 23.9.0
  epoch: 1
  description: "A system-level, binary package and environment manager running on all major operating systems and platforms."
  copyright:
    - license: BSD-3-Clause
  options:
    no-provides: true
    no-depends: true
  dependencies:
    runtime:
      - python3
      - py3-packaging
      - py3-requests
      - py3-ruamel-yaml
      - py3-pluggy
      - py3-tqdm

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - bash
      - wget
      - python3
      - py3-pip
      - py3-hatchling
      - py3-wheel
      - py3-hatch
      - py3-charset-normalizer
      - py3-urllib3
      - py3-idna
      - py3-requests
      - py3-zstandard
  environment:
    # This is needed to work around the error "ValueError: ZIP does not support timestamps before 1980"
    SOURCE_DATE_EPOCH: 315532800

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/conda/conda
      tag: ${{package.version}}
      expected-commit: cfd33ed663b340ce522e9f5e83037dbe2ed73d5b

  - runs: |
      pip install conda-package-handling
      hatch build
      python3 -m installer -d "${{targets.destdir}}" dist/conda*.whl

update:
  enabled: true
  github:
    identifier: conda/conda
