package:
  name: consul-1.15
  version: 1.15.6
  # When bumping the version check if the CVE/GHSA mitigations below can be removed.
  epoch: 3
  description: Consul is a distributed, highly available, and data center aware solution to connect and configure applications across dynamic, distributed infrastructure.
  copyright:
    - license: MPL-2.0
  dependencies:
    provides:
      - consul=1.15.999 # This is because we had a 1.15.0 consul package, remove in 1.17+

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hashicorp/consul
      tag: v${{package.version}}
      expected-commit: b78855498dcab1be712803054f7b395c81848d87
      destination: ${{package.name}}

  - working-directory: ${{package.name}}
    pipeline:
      - runs: |
          # Handle CVE-2022-41723 CVE-2023-39325 and CVE-2023-3978
          go get golang.org/x/net@v0.17.0
          go mod tidy

          make linux
      - runs: |
          mkdir -p ${{targets.destdir}}/bin

          # The docker-entrypoint.sh expects the binary to be in /bin so put it there
          mv ./pkg/bin/linux_*/consul ${{targets.destdir}}/bin/consul
      - uses: strip

subpackages:
  - name: ${{package.name}}-oci-entrypoint
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ${{package.name}}/.release/docker/docker-entrypoint.sh "${{targets.subpkgdir}}/usr/bin/"
    dependencies:
      provides:
        - consul-oci-entrypoint=1.15.999 # This is because we had a 1.15.0 consul package, remove in 1.17+
      runtime:
        - consul-1.15
        - busybox
        - dumb-init
        - su-exec
        - libcap-utils

  - name: ${{package.name}}-oci-entrypoint-compat
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/usr/local/bin"
          ln -s /usr/bin/docker-entrypoint.sh "${{targets.subpkgdir}}/usr/local/bin/"
    dependencies:
      provides:
        - consul-oci-entrypoint-compat=1.15.999 # This is because we had a 1.15.0 consul package, remove in 1.17+
      runtime:
        - consul-1.15-oci-entrypoint

update:
  enabled: true
  github:
    identifier: hashicorp/consul
    strip-prefix: v
    tag-filter: v1.15.
