package:
  name: containerd
  version: 1.7.7
  epoch: 2
  description: An open and reliable container runtime
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - runc

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - bash
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/containerd/containerd
      tag: v${{package.version}}
      expected-commit: 8c087663b0233f6e6e2f4515cee61d49f14746a8

  - runs: |
      # Handle CVE-2022-41723 CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy
      go mod vendor

      make VERSION="v${{package.version}}"

  # Set up default config
  - runs: |
      mkdir -p "${{targets.destdir}}"/etc/containerd
      ./bin/containerd config default > "${{targets.destdir}}"/etc/containerd/config.toml

  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/bin
      install -sm755 ./bin/* "${{targets.destdir}}"/usr/bin/

  - uses: strip

data:
  - name: bins
    items:
      ctr: client for containerd
      containerd-stress: stress utility
      containerd-shim: shim
      containerd-shim-runc-v1: runc shim v1
      containerd-shim-runc-v2: runc shim v2

subpackages:
  - range: bins
    name: ${{range.key}}
    description: ${{range.value}}
    pipeline:
      - runs: |
          install -Dm755 "${{targets.destdir}}"/usr/bin/${{range.key}} "${{targets.subpkgdir}}"/usr/bin/${{range.key}}

update:
  enabled: true
  github:
    identifier: containerd/containerd
    strip-prefix: v
