package:
  name: coredns
  version: 1.11.1
  epoch: 5
  description: CoreDNS is a DNS server that chains plugins
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - wolfi-baselayout
      - build-base
      - ca-certificates-bundle
      - busybox
      - bash
      - make
      - libcap-utils
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/coredns/coredns
      tag: v${{package.version}}
      expected-commit: ae2bbc29be1aaae0b3ded5d188968a6c97bb3144

  - runs: |
      # Handle CVE-2022-41723 CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy

      # Ensures plugins get included
      make check

  - uses: go/build
    with:
      go-package: go-1.20 # pin to a specific version of Go as not working with go-1.21 yet
      packages: .
      output: coredns
      ldflags: -s -w -X github.com/coredns/coredns/coremain.GitCommit=v${{package.version}}

  - uses: strip

  # This MUST run after strip, which strips capabilities too!
  - runs: setcap cap_net_bind_service=+ep "${{targets.destdir}}/usr/bin/coredns"

update:
  enabled: true
  github:
    identifier: coredns/coredns
    strip-prefix: v
