package:
  name: cosign
  version: 2.2.0
  epoch: 5
  description: Container Signing
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/sigstore/cosign/archive/v${{package.version}}/cosign-v${{package.version}}.tar.gz
      expected-sha256: eceb7c537211e950f01b712b29a58164ed023ce5369b7e6fcfd7a730abbeab32

  - uses: go/build
    with:
      packages: ./cmd/cosign
      output: cosign
      ldflags: -s -w -X sigs.k8s.io/release-utils/version.gitVersion=${{package.version}}
      # CVE-2023-39325 and CVE-2023-3978
      deps: golang.org/x/net@v0.17.0

  - uses: strip

update:
  enabled: true
  github:
    identifier: sigstore/cosign
    strip-prefix: v
