package:
  name: cqlsh
  version: 4.1.2
  epoch: 1
  description: CQL shell for apache cassandra
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - py3-setuptools
      - python3-dev
      - python3
      - cython

pipeline:
  - uses: fetch
    with:
      expected-sha256: e9a90b2fe53ed69a52e8f313f2a272f4e593e24c270054030a70e1f2c24088c1
      uri: https://github.com/apache/cassandra/archive/cassandra-${{package.version}}.tar.gz

  - runs: |
      (cd ./pylib && python setup.py build)

      mkdir -p ${{targets.destdir}}/usr/bin
      cp ./bin/cqlsh ${{targets.destdir}}/usr/bin/cqlsh
      cp ./bin/cqlsh.py ${{targets.destdir}}/usr/bin/cqlsh
      (cd ./pylib &&  python setup.py install --prefix=/usr --root="${{targets.destdir}}")

  - uses: strip

update:
  enabled: true
  manual: true
  github:
    identifier: apache/cassandra
    strip-prefix: cassandra-
    use-tag: true
