package:
  name: crfsuite
  version: 0.12
  epoch: 0
  description: An implementation of Conditional Random Fields (CRFs) for labeling sequential data
  copyright:
    - license: BSD

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - libtool
      - bash
      - m4
      - liblbfgs-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/chokkan/crfsuite/archive/${{package.version}}.tar.gz
      expected-sha256: ab83084ed5d4532ec772d96c3e964104d689f2c295915e80299ea3c315335b00

  - uses: patch
    with:
      patches: fix-autoconf-automake.patch

  - runs: autoupdate

  - runs: ./autogen.sh

  - runs: autoreconf -vif

  - uses: autoconf/configure
    with:
      opts: |
        --disable-sse2

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: false
