package:
  name: crossplane
  version: 1.13.2
  epoch: 1
  description: Cloud Native Control Planes
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/crossplane/crossplane
      tag: v${{package.version}}
      expected-commit: 8c7fb7f2fa23ef5937a36260a80a87428f9d1f2b

  - runs: |
      mkdir -p ${{targets.destdir}}/crds
      cp cluster/crds/* ${{targets.destdir}}/crds

      mkdir -p ${{targets.destdir}}/webhookconfigurations
      cp cluster/webhookconfigurations/* ${{targets.destdir}}/webhookconfigurations

  - uses: go/build
    with:
      packages: ./cmd/crossplane
      output: crossplane
      # CVE-2023-39325 and CVE-2023-3978
      deps: golang.org/x/net@v0.17.0
      ldflags: -w

  - uses: strip

subpackages:
  - name: crossplane-xfn
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/xfn
          output: xfn
          subpackage: "true"
          # CVE-2023-39325 and CVE-2023-3978
          deps: golang.org/x/net@v0.17.0 github.com/cyphar/filepath-securejoin@v0.2.4
          ldflags: -w
      - uses: strip

update:
  enabled: true
  github:
    identifier: crossplane/crossplane
    strip-prefix: v
