package:
  name: crossplane-provider-aws
  version: 0.42.0
  epoch: 1
  description: Official AWS Provider for Crossplane by Upbound
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - terraform-provider-aws

environment:
  contents:
    packages:
      - up
      - build-base
      - bash
      - go
      - busybox
      - curl
      - gzip
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/upbound/provider-aws
      tag: v${{package.version}}
      expected-commit: 5f6e93ead12cfa7e6025a55e37fde9363b9fb0f7

  - runs: |
      # `make` downloads `up`, unless we move our prebuilt `up` to where it expects it.
      GOARCH=$(go env GOARCH)
      UP_VERSION=$(up --version)
      echo "Using up ${UP_VERSION}"

      # They use hostarch instead of goarch here which uses aarch64 instead of arm64
      hostarch=$(uname -m)
      mkdir -p ./.cache/tools/linux_${hostarch}

      cp $(which up) ./.cache/tools/linux_${hostarch}/up-${UP_VERSION}

      # Mitigate CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy

      make UP_VERSION=${UP_VERSION}

      mkdir -p "${{targets.destdir}}"/usr/bin/
      cp ./_output/bin/linux_${GOARCH}/monolith "${{targets.destdir}}"/usr/bin/provider

  - uses: strip

data:
  - name: packages
    items:
      family: provider-family-aws
      # List from: https://github.com/gitops-bridge-dev/gitops-bridge-argocd-control-plane-template/blob/main/charts/addons/crossplane/resources/values.yaml
      cloudfront: provider-aws-cloudfront
      cloudwatchlogs: provider-aws-cloudwatchlogs
      dynamodb: provider-aws-dynamodb
      ec2: provider-aws-ec2
      eks: provider-aws-eks
      firehose: provider-aws-firehose
      iam: provider-aws-iam
      kms: provider-aws-kms
      lambda: provider-aws-lambda
      rds: provider-aws-rds
      s3: provider-aws-s3
      sns: provider-aws-sns
      sqs: provider-aws-sqs

subpackages:
  - name: crossplane-provider-aws-${{range.key}}
    range: packages
    pipeline:
      - runs: |
          up xpkg xp-extract xpkg.upbound.io/upbound/${{range.value}}:v${{package.version}}
          mkdir -p "${{targets.subpkgdir}}"
          gunzip out.gz -c > "${{targets.subpkgdir}}"/package.yaml

update:
  enabled: true
  github:
    identifier: upbound/provider-aws
    strip-prefix: v
