package:
  name: cython
  version: 3.0.4
  epoch: 0
  description: Cython is an optimising static compiler for both the Python & the extended Cython programming languages.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - py3-setuptools
      - python3-dev
      - python3

pipeline:
  - uses: fetch
    with:
      expected-sha256: d22c3fd0141860ef892f51ea834556ee42c3c9f83739ad92187dcf0b9f938786
      uri: https://github.com/cython/cython/archive/${{package.version}}.tar.gz

  - runs: |
      python setup.py build
      python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: cython/cython
