package:
  name: cython-0
  version: 0.29.36
  epoch: 2
  description: Cython is an optimising static compiler for both the Python & the extended Cython programming languages.
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - cython=${{package.version}}-r${{package.epoch}}

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - py3-setuptools
      - python3-dev
      - python3

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 702bbc80fe2e346c4ddc58f074e0054da56e0ced
      repository: https://github.com/cython/cython
      tag: ${{package.version}}

  - runs: |
      python setup.py build
      python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: cython/cython
    use-tag: true
    tag-filter: 0.
