package:
  name: dex
  # When bumping the version check if the GHSA mitigations below can be removed.
  version: 2.37.0
  epoch: 7
  description: OpenID Connect (OIDC) identity and OAuth 2.0 provider with pluggable connectors
  copyright:
    - license: Apache-2.0
  checks:
    disabled:
      - srv

environment:
  contents:
    packages:
      - wolfi-baselayout
      - busybox
      - build-base
      - go
      - git
      - ca-certificates-bundle

pipeline:
  # We can't use go/install because this requires a specific go version
  - uses: git-checkout
    with:
      repository: https://github.com/dexidp/dex
      tag: v${{package.version}}
      expected-commit: 08bb7fb98b164ab078be17ecda4077b2d21c9bb3
      destination: dex

  - runs: |
      cd dex

      # These build commands are adapted from the upstream `make release-binary` target.
      export GOBIN="$GOPATH/bin"
      LD_FLAGS="-w -X main.version=v${{package.version}} -extldflags \"-static\""

      # Mitigate CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy

      go build -o "$GOBIN/dex" -v -ldflags "$LD_FLAGS" ./cmd/dex
      go build -o "$GOBIN/docker-entrypoint" -v -ldflags "$LD_FLAGS" ./cmd/docker-entrypoint

      mkdir -p ${{targets.destdir}}/usr/bin
      mkdir -p ${{targets.destdir}}/srv/dex
      mkdir -p ${{targets.destdir}}/etc/dex
      mkdir -p ${{targets.destdir}}/var/dex

      mv "$GOBIN/dex" ${{targets.destdir}}/usr/bin/
      mv "$GOBIN/docker-entrypoint" ${{targets.destdir}}/usr/bin/
      mv web ${{targets.destdir}}/srv/dex/
      mv config.docker.yaml ${{targets.destdir}}/etc/dex/

  - uses: strip

update:
  enabled: true
  github:
    identifier: dexidp/dex
    strip-prefix: v
    tag-filter: v
