package:
  name: diffoscope
  version: "249"
  epoch: 1
  description: "In-depth comparison of files, archives, and directories."
  copyright:
    - license: GPL-3.0-or-later
  dependencies:
    runtime:
      - python3
      - py3-libarchive-c
      - py3-magic

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-setuptools
      - py3-docutils
      - py3-gpep517
      - py3-wheel

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/d/diffoscope/diffoscope-${{package.version}}.tar.gz
      expected-sha256: bc4d8cb3198025013784ef7e3fa61b7a642de39e5b790c45d7c29d153306fbdd

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 31806
