package:
  name: dive
  version: 0.11.0
  epoch: 8
  description: A tool for exploring each layer in a docker image
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/wagoodman/dive
      tag: v${{package.version}}
      expected-commit: 800398060434ce8dfda6b4d182b72e2a9724e9f6
      destination: dive

  - runs: |
      cd dive

      # GHSA-77vh-xpmg-72qh
      go get -u github.com/opencontainers/image-spec@v1.0.2

      # CVE-2021-3121
      go get -u github.com/golang/protobuf@v1.5.3

      # GHSA-c3h9-896r-86jm
      go get -u github.com/gogo/protobuf@v1.3.2

      # GHSA-h86h-8ppg-mxmh
      # GHSA-83g2-8m93-v3w7
      # GHSA-69cg-p879-7622
      # GHSA-vvpx-j8f3-3w6h
      # CVE-2023-39325 and CVE-2023-3978
      go get -u golang.org/x/net@v0.17.0

      go mod tidy
      go mod vendor

  - uses: go/build
    with:
      packages: .
      output: dive
      modroot: dive
      ldflags: -w -X main.version=v${{package.version}} -X main.commit=$(git rev-parse HEAD) -X main.buildTime=$(date +%F-%T)

  - uses: strip

update:
  enabled: true
  github:
    identifier: wagoodman/dive
    strip-prefix: v
