package:
  name: docker-credential-gcr
  version: 2.1.19
  epoch: 0
  description: A Docker credential helper for GCR users
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/GoogleCloudPlatform/docker-credential-gcr
      tag: v${{package.version}}
      expected-commit: d429491d2432009f0fbdd48faa60220c6afed262

  - runs: |
      # CVE-2023-39325 and CVE-2023-3978
      go get -u golang.org/x/net@v0.17.0

      go mod tidy -compat=1.17
      go mod vendor

  - uses: go/build
    with:
      packages: .
      output: docker-credential-gcr
      ldflags: -s -w -X github.com/GoogleCloudPlatform/docker-credential-gcr/config.Version=${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: GoogleCloudPlatform/docker-credential-gcr
    strip-prefix: v
    tag-filter: v
