package:
  name: envoy
  version: 1.27.2
  epoch: 0
  description: Cloud-native high-performance edge/middle/service proxy
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - wolfi-baselayout
      - binutils
      - build-base
      - git
      - bazel-6
      - openjdk-11
      - bash
      - libtool
      - cmake
      - samurai
      - python3-dev
      - clang~15
      - llvm15
      - llvm15-dev
      - llvm-lld-15
      - llvm15-tools
      - llvm15-cmake-default
      - coreutils
      - patch
      # We need to stick to gcc 12 for now, envoy doesn't build with gcc >= 13
      - gcc-12-default

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/envoyproxy/envoy
      tag: v${{package.version}}
      expected-commit: ae07f9a11715245f7d25d2a13699c260c2ae8ebb
      destination: envoy

  - runs: |
      # Apply https://github.com/envoyproxy/envoy/pull/29261/files so build
      # can work with make > 4.3
      cp -f luajit.patch envoy/bazel/foreign_cc

      export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
      mkdir -p .cache/bazel/_bazel_root

      cd envoy
      # The Python interpreter complains about being run as root, there's a flag to pass to disable that warning.
      sed -i 's/envoy_dependencies_extra()/envoy_dependencies_extra(ignore_root_user_error=True)/g' WORKSPACE

      ./bazel/setup_clang.sh /usr
      echo "build --config=clang" >> user.bazelrc

      bazel build --verbose_failures -c opt envoy

      mkdir -p ${{targets.destdir}}/usr/bin/
      mv bazel-bin/source/exe/envoy-static ${{targets.destdir}}/usr/bin/envoy

      # We no longer need this cache dir, which has some writable files.
      rm -rf ../.cache/bazel/_bazel_root

  - uses: strip

subpackages:
  - name: envoy-oci-entrypoint
    description: Entrypoint for using Envoy in OCI containers
    dependencies:
      runtime:
        - busybox
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/var/lib/envoy/init
          cp envoy/ci/docker-entrypoint.sh ${{targets.subpkgdir}}/var/lib/envoy/init/envoy-entrypoint.sh
          chmod +x ${{targets.subpkgdir}}/var/lib/envoy/init/envoy-entrypoint.sh

  - name: envoy-config
    description: Default Envoy configuration
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/etc/envoy
          cp envoy/configs/envoyproxy_io_proxy.yaml ${{targets.subpkgdir}}/etc/envoy/envoy.yaml

update:
  enabled: true
  github:
    identifier: envoyproxy/envoy
    strip-prefix: v
