package:
  name: exim
  version: 4.96.2
  epoch: 0
  description: Message Transfer Agent
  copyright:
    - license: GPL-2.0-or-later
  checks:
    disabled:
      - setuidgid

environment:
  contents:
    packages:
      - wolfi-baselayout
      - bash
      - busybox
      - tdb-dev
      - tdb
      - gawk
      - libidn-dev
      - libspf2-dev
      - linux-headers
      - mariadb-connector-c-dev
      - openssl-dev>3
      - pcre2-dev
      - perl
      - postgresql-15-dev
      - sqlite-dev
      - build-base
      - ca-certificates-bundle
  accounts:
    users:
      - username: exim
        uid: 1001

pipeline:
  - uses: fetch
    with:
      expected-sha256: 038e327e8d1e93d005bac9bb06fd22aec44d5028930d6dbe8817ad44bbfc1de6
      uri: https://ftp.exim.org/pub/exim/exim4/exim-${{package.version}}.tar.xz

  - uses: patch
    with:
      patches: dr-tables-typo.patch

  - runs: |
      cp exim.Makefile Local/Makefile

      sed -i \
        -e 's/-lnsl//g' \
        -e 's/^HAVE_ICONV.*$//' \
        OS/Makefile-Linux

      # This is kind of hacky, but the makefile tests the binary and it won't run without a user configured
      make makefile
      make

  - runs: |
      install -m750 -D -g mail -d "${{targets.destdir}}"/etc/mail
      make DESTDIR="${{targets.destdir}}" INSTALL_ARG="-no_symlink -no_chown exim" install
      install -D -m644 doc/exim.8 "${{targets.destdir}}"/usr/share/man/man8/exim.8
      cd "${{targets.destdir}}"/usr/sbin
      mv exim-* exim
      chmod u+s exim
      for i in mailq rmail rsmtp runq sendmail newaliases; do
        ln -s exim $i
      done
      # Fix clamav local socket path, Add variant to spamd address
      sed -i \
        -e 's~# av_scanner = clamd:/tmp/clamd~# av_scanner = clamd:/run/clamav/clamd.sock~' \
        -e '/# spamd_address = 127.0.0.1 783/a# spamd_address = 127.0.0.1 11333 variant=rspamd' \
        "${{targets.destdir}}"/etc/${{package.name}}/${{package.name}}.conf
      # Create subdirs for logs and extensions
      install -dm750 -o ${{package.name}} -g mail "${{targets.destdir}}"/var/log/${{package.name}}
      mkdir -p "${{targets.destdir}}"/usr/lib/${{package.name}}

  - uses: strip

subpackages:

update:
  enabled: true
  release-monitor:
    identifier: 768
