package:
  name: external-secrets-operator
  version: 0.9.6
  epoch: 0
  description: Integrate external secret management systems with Kubernetes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - git
      - bash
      - go
      - yq

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/external-secrets/external-secrets
      tag: v${{package.version}}
      expected-commit: d42ccaaf781e8c0fcecb65fb936191a0bbd787e4

  - runs: |
      # Mitigate CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy

      make build-$(go env GOARCH)
      mkdir -p ${{targets.destdir}}/usr/bin
      install -m755 -D bin/external-secrets-$(go env GOOS)-$(go env GOARCH) "${{targets.destdir}}"/usr/bin/external-secrets

  - uses: strip

update:
  enabled: true
  github:
    identifier: external-secrets/external-secrets
    strip-prefix: v
    tag-filter: v
