package:
  name: external-dns
  version: 0.13.6
  epoch: 5
  description: Configure external DNS servers (AWS Route53, Google CloudDNS and others) for Kubernetes Ingresses and Services.
  copyright:
    - license: Apache-2.0
      paths:
        - "*"

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/external-dns
      tag: v${{package.version}}
      expected-commit: 0483ffde22e60436f16be154b9fe1a388a1400d0

  - runs: |
      # Mitigate CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy

      # Our global LDFLAGS conflict with a Makefile parameter
      unset LDFLAGS
      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      mv build/external-dns ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/external-dns
    strip-prefix: v
    tag-filter: v
