package:
  name: flux-source-controller
  version: 1.1.2
  epoch: 1
  description: The GitOps Toolkit source management component
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - gcc
      - clang-16
      - llvm-lld-16

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/fluxcd/source-controller
      tag: v${{package.version}}
      expected-commit: 8b83c8bf8ed1f44c3f2e4a02ea980fcddabb67dc

  - runs: |
      # CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0

      mkdir -p "${{targets.destdir}}"/usr/bin
      CGO_ENABLED=1 CGO_LDFLAGS="-static -fuse-ld=lld" go build \
        -ldflags "-s -w" \
        -tags 'netgo,osusergo,static_build' \
        -trimpath -o "${{targets.destdir}}"/usr/bin/source-controller .

  - uses: strip

update:
  enabled: true
  github:
    identifier: fluxcd/source-controller
    strip-prefix: v
    use-tag: true
    tag-filter: v
