package:
  name: flux-helm-controller
  version: 0.36.2
  epoch: 1
  description: The GitOps Toolkit Helm reconciler, for declarative Helming
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/fluxcd/helm-controller
      tag: v${{package.version}}
      expected-commit: 7f3d5141f96c0374e01d6e644c8b11502f2352cf

  - uses: go/build
    with:
      packages: .
      output: helm-controller
      ldflags: -s -w
      # CVE-2023-39325 and CVE-2023-3978
      deps: golang.org/x/net@v0.17.0

  - uses: strip

update:
  enabled: true
  github:
    identifier: fluxcd/helm-controller
    strip-prefix: v
    use-tag: true
    tag-filter: v
