package:
  name: flux-notification-controller
  version: 1.1.0
  epoch: 4
  description: The GitOps Toolkit event forwarded and notification dispatcher
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/fluxcd/notification-controller
      tag: v${{package.version}}
      expected-commit: 7de11b33d94c017dc2ad47e13f93fcf13667c4d4

  - runs: |
      # CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0

      mkdir -p "${{targets.destdir}}"/usr/bin
      CGO_ENABLED=0 go build \
        -trimpath -a -o "${{targets.destdir}}"/usr/bin/notification-controller .

  - uses: strip

update:
  enabled: true
  github:
    identifier: fluxcd/notification-controller
    strip-prefix: v
    use-tag: true
    tag-filter: v
