package:
  name: flux-image-reflector-controller
  version: 0.30.0
  epoch: 4
  description: GitOps Toolkit controller that scans container registries
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/fluxcd/image-reflector-controller
      tag: v${{package.version}}
      expected-commit: 2230328db8f6ee6d658a3f548d5a80e9b3a83233

  - uses: go/build
    with:
      packages: .
      output: image-reflector-controller
      ldflags: -s -w
      # CVE-2023-39325 and CVE-2023-3978
      deps: golang.org/x/net@v0.17.0

  - uses: strip

update:
  enabled: true
  github:
    identifier: fluxcd/image-reflector-controller
    strip-prefix: v
    use-tag: true
    tag-filter: v
