package:
  name: flux-kustomize-controller
  version: 1.1.1
  epoch: 1
  description: The GitOps Toolkit Kustomize reconciler
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - git
      - gnupg
      - gpg
      - gpg-agent
      - gnupg-gpgconf
      - gnupg-utils
      - gpgsm
      - gpgv
      - gpg-wks-server
      - gnupg-wks-client
      - tzdata
      - openssh-client

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/fluxcd/kustomize-controller
      tag: v${{package.version}}
      expected-commit: 049d1d3d35acc74812cacbc62de5b91eca531c34

  - uses: go/build
    with:
      packages: .
      output: kustomize-controller
      ldflags: -s -w
      # CVE-2023-39325 and CVE-2023-3978
      deps: golang.org/x/net@v0.17.0

  - uses: strip

update:
  enabled: true
  github:
    identifier: fluxcd/kustomize-controller
    strip-prefix: v
    use-tag: true
    tag-filter: v
