package:
  name: flux-image-automation-controller
  version: 0.36.1
  epoch: 3
  description: GitOps Toolkit controller that patches container image tags in Git
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - llvm-lld-16
      - gcc
      - clang-16

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/fluxcd/image-automation-controller
      tag: v${{package.version}}
      expected-commit: 3d34d8fcd5686c5fecc3547bd166aef1f9e1eae8

  - runs: |
      # CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0

      mkdir -p "${{targets.destdir}}"/usr/bin
      CGO_ENABLED=1 CGO_LDFLAGS="-static -fuse-ld=lld" go build \
        -ldflags "-s -w" \
        -tags 'netgo,osusergo,static_build' \
        -trimpath -o "${{targets.destdir}}"/usr/bin/image-automation-controller .

  - uses: strip

subpackages:
  - name: flux-image-automation-controller-compat
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/local/bin
          # The upstream helm chart assumes the binary is in /.
          ln -sf /usr/bin/image-automation-controller ${{targets.subpkgdir}}/usr/local/bin/image-automation-controller
    dependencies:
      runtime:
        - flux-image-automation-controller

update:
  enabled: true
  github:
    identifier: fluxcd/image-automation-controller
    strip-prefix: v
    use-tag: true
    tag-filter: v
