package:
  name: fuse-overlayfs-snapshotter
  version: 1.0.7
  epoch: 2
  description: fuse-overlayfs plugin for rootless containerd
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - fuse-overlayfs

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - go
      - fuse3-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/containerd/fuse-overlayfs-snapshotter
      expected-commit: 04efe648d0dfda56061c9759e9db08a6584b296c
      tag: v${{package.version}}

  - runs: |
      # Mitigate CVE-2023-39325, CVE-2023-3978, CVE-2023-44487
      go get golang.org/x/net@v0.17.0
      go mod tidy

      make bin/containerd-fuse-overlayfs-grpc

      make install BINDIR="${{targets.destdir}}"/usr/bin

  - uses: strip

update:
  enabled: true
  github:
    identifier: containerd/fuse-overlayfs-snapshotter
    strip-prefix: v
