package:
  name: gatekeeper-3.13
  version: 3.13.3
  epoch: 0
  description: Gatekeeper - Policy Controller for Kubernetes
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - gatekeeper=3.13.999

environment:
  contents:
    packages:
      - wolfi-baselayout
      - busybox
      - build-base
      - go
      - ca-certificates-bundle

pipeline:
  # We can't use go/install because this requires specific ldflags to set the version
  - uses: git-checkout
    with:
      repository: https://github.com/open-policy-agent/gatekeeper
      tag: v${{package.version}}
      expected-commit: 71a3f00fc5a50ae9de9fe16741f88482d1843cc4
      destination: gatekeeper

  - runs: |
      cd gatekeeper
      FRAMEWORKS_VERSION=$(go list -f '{{ .Version }}' -m github.com/open-policy-agent/frameworks/constraint)
      OPA_VERSION=$(go list -f '{{ .Version }}' -m github.com/open-policy-agent/opa)
      CGO_ENABLED=0 GO111MODULE=on go build -mod vendor -a -ldflags "-w -X github.com/open-policy-agent/gatekeeper/pkg/version.Version=v${{package.version}} -X main.frameworksVersion=${FRAMEWORKS_VERSION} -X main.opaVersion=${OPA_VERSION}" -o manager
      mkdir -p ${{targets.destdir}}/usr/bin
      install -Dm755 ./manager ${{targets.destdir}}/usr/bin/manager

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}
          ln -sf /usr/bin/manager ${{targets.subpkgdir}}/manager
    dependencies:
      provides:
        - gatekeeper-compat=3.13.999

update:
  enabled: true
  github:
    identifier: open-policy-agent/gatekeeper
    strip-prefix: v
    use-tag: true
    tag-filter: v3.13.
