package:
  name: git-lfs
  version: 3.4.0
  epoch: 4
  description: "large file support for git"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - git

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - go
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/git-lfs/git-lfs
      tag: v${{package.version}}
      expected-commit: d06d6e9efd78ff4f958b072146ce167d87f60285
      destination: git-lfs

  - runs: |
      cd git-lfs
      # Mitigate CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy

  - runs: |
      cd git-lfs
      make EXTRA_GO_FLAGS="-v -tags netcgo" EXTRA_LD_FLAGS="-s -w -extldflags '${LDFLAGS}'" VERSION="v${{package.version}}"
      install -Dm755 bin/git-lfs "${{targets.destdir}}"/usr/bin/git-lfs

  - uses: strip

update:
  enabled: true
  github:
    identifier: git-lfs/git-lfs
    tag-filter: v
    strip-prefix: v
