package:
  name: gitness
  version: 3.0.0_beta2
  epoch: 0
  description: Gitness is an Open Source developer platform with Source Control management, Continuous Integration and Continuous Delivery.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go
      - build-base
      - yarn
      - nodejs
      - protoc
      - protobuf
      - protoc-gen-go
      - protoc-gen-go-grpc

var-transforms:
  - from: ${{package.version}}
    match: _beta
    replace: -beta.
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      # Hack until they cut a release
      repository: https://github.com/harness/gitness/
      expected-commit: 1c762c6802b391ef2f3346886629bb0c1d514e24
      tag: v${{vars.mangled-package-version}}

  - runs: |
      cd web
      yarn && yarn build && yarn cache clean
      cd ..

      # Mitigate CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0

      go mod tidy

      make dep
      make tools
      make build

      mkdir -p ${{targets.destdir}}/usr/bin
      mv gitness ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: harness/gitness
    strip-prefix: v
