package:
  name: gomplate
  version: 3.11.5
  epoch: 6
  description: A go templating utility.
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - wolfi-baselayout
      - busybox
      - build-base
      - go-1.20 #NOTE: This should move back to "go" on next release
      - git
      - ca-certificates-bundle

pipeline:
  # We can't use go/install because this requires a specific go version
  - uses: git-checkout
    with:
      repository: https://github.com/hairyhenderson/gomplate
      tag: v${{package.version}}
      expected-commit: ea986e7404d1dcacf41d6a9afea306da915c95fe

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin

      # Mitigate CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy

      go build -o ${{targets.destdir}}/usr/bin \
        -ldflags "-w -s -X github.com/hairyhenderson/gomplate/v3/version.Version=${{package.version}} \
        -X github.com/hairyhenderson/gomplate/v3/version.GitCommit=$(git rev-parse --short HEAD)" \
        github.com/hairyhenderson/gomplate/v3/cmd/gomplate

      # Test that the binary can be run, since there have been issues with the
      # Go version used by the tool that only manifest at runtime.
      ${{targets.destdir}}/usr/bin/gomplate -i 'the answer is: {{ mul 6 7 }}'

update:
  enabled: true
  github:
    identifier: hairyhenderson/gomplate
    strip-prefix: v
