package:
  name: httpie
  version: 3.2.2
  epoch: 1
  description: "HTTPie for Terminal — modern, user-friendly command-line HTTP client for the API era. JSON support, colors, sessions, downloads, plugins & more."
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-pip
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/httpie/httpie
      tag: ${{package.version}}
      expected-commit: 29de4ce1151936856cda417767f8c507fc2c201c

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: httpie/httpie
    use-tag: true
