package:
  name: karpenter
  version: 0.31.1
  epoch: 1
  description: Karpenter is a Kubernetes Node Autoscaler built for flexibility, performance, and simplicity.
  copyright:
    - license: Apache-2.0
      paths:
        - "*"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aws/karpenter
      tag: v${{package.version}}
      expected-commit: 61b3e1eca95b2ad702dee221f35041a494f1141f

  - uses: go/build
    with:
      # CVE-2023-39325 and CVE-2023-3978
      deps: golang.org/x/net@v0.17.0
      packages: ./cmd/controller
      output: controller

  - uses: strip

update:
  enabled: true
  github:
    identifier: aws/karpenter
    strip-prefix: v
