package:
  name: kor
  version: 0.2.4
  epoch: 0
  description: A Golang Tool to discover unused Kubernetes Resources
  copyright:
    - license: MIT License

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/yonahd/kor
      tag: v${{package.version}}
      expected-commit: ec0b8fab7731e65decdf838019e9ec0834bac5ec

  - uses: go/build
    with:
      modroot: .
      packages: .
      ldflags: -w
      output: kor
      deps: golang.org/x/net@v0.17.0

  - uses: strip

update:
  enabled: true
  github:
    identifier: yonahd/kor
    strip-prefix: v
