package:
  name: kpt
  version: 1.0.0_beta46
  epoch: 0
  description: Automate Kubernetes Configuration Editing
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - make

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/GoogleContainerTools/kpt
      tag: v1.0.0-beta.46
      expected-commit: 8b5e2f5450de1d468307d8026790914c92a25c1f

  - runs: |
      # Mitigate GHSA-hqxw-f8mx-cpmw
      go get github.com/docker/distribution@v2.8.2
      # Mitigate CVE-2023-39325, CVE-2023-3978, CVE-2023-44487
      go get golang.org/x/net@v0.17.0

      go mod tidy
      go mod vendor

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      make GOBIN="${{targets.destdir}}"/usr/bin build

  - uses: strip

update:
  enabled: true
  manual: true # The beta versioning here breaks our automation
  github:
    identifier: GoogleContainerTools/kpt
    strip-prefix: v
    tag-filter: v
    use-tag: true
