package:
  name: kubernetes-csi-external-resizer
  version: 1.9.0
  epoch: 3
  description: Sidecar container that watches Kubernetes PersistentVolumeClaims objects and triggers controller side expansion operation against a CSI endpoint
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - wolfi-baselayout
      - busybox
      - build-base
      - go
      - ca-certificates-bundle

pipeline:
  # We can't use go/install because this requires specific ldflags to set the version
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-csi/external-resizer
      tag: v${{package.version}}
      expected-commit: 42ecc22863e4d53d1e91be9223cc5a97c3c65872

  - runs: |
      # CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod vendor

      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      install -Dm755 ./bin/csi-resizer ${{targets.destdir}}/usr/bin/csi-resizer

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-csi/external-resizer
    strip-prefix: v
    use-tag: true
    tag-filter: v
