package:
  name: kube-state-metrics
  version: 2.10.0
  epoch: 4
  description: Add-on agent to generate and expose cluster-level metrics.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes/kube-state-metrics
      tag: v${{package.version}}
      expected-commit: 25fb4fa0767de7ee314500fcb7481ca7b3a55a35

  - runs: |
      # CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0

      mkdir -p ${{targets.destdir}}/usr/bin
      make build-local
      cp kube-state-metrics ${{targets.destdir}}/usr/bin

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes/kube-state-metrics
    strip-prefix: v
    tag-filter: v
