package:
  # Supported versions policy: https://kubernetes-csi.github.io/docs/node-driver-registrar.html
  name: kubernetes-csi-node-driver-registrar-2.9
  version: 2.9.0
  epoch: 5
  description: Sidecar container that registers a CSI driver with the kubelet using the kubelet plugin registration mechanism.
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - kubernetes-csi-node-driver-registrar=${{package.full-version}}

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-csi/node-driver-registrar
      tag: v${{package.version}}
      expected-commit: deed783528cd828baedc5493a866a0217f7b08fe

  - uses: go/build
    with:
      packages: ./cmd/csi-node-driver-registrar
      ldflags: "-s -w -X main.version=v${{package.version}} -extldflags '-static'"
      vendor: "true"
      output: csi-node-driver-registrar
      # CVE-2023-39325 and CVE-2023-3978
      deps: golang.org/x/net@v0.17.0

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          # The helm chart expects the binaries to be in / instead of /usr/bin
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/csi-node-driver-registrar ${{targets.subpkgdir}}/csi-node-driver-registrar
    dependencies:
      provides:
        - kubernetes-csi-node-driver-registrar-compat=${{package.full-version}}

update:
  enabled: true
  github:
    identifier: kubernetes-csi/node-driver-registrar
    strip-prefix: v
    tag-filter: v2.9.
