package:
  name: kubernetes-csi-external-attacher-4.3
  version: 4.3.0
  epoch: 9
  description: Sidecar container that watches Kubernetes VolumeAttachment objects and triggers ControllerPublish/Unpublish against a CSI endpoint
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - kubernetes-csi-external-attacher=${{package.full-version}}

environment:
  contents:
    packages:
      - wolfi-baselayout
      - busybox
      - build-base
      - go
      - ca-certificates-bundle

pipeline:
  # We can't use go/install because this requires specific ldflags to set the version
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-csi/external-attacher
      tag: v${{package.version}}
      expected-commit: 910cd35d72e6a99cc7b8451a5065aecc11bd7fff

  - runs: |
      # CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod vendor

      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      install -Dm755 ./bin/csi-attacher ${{targets.destdir}}/usr/bin/csi-attacher

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-csi/external-attacher
    strip-prefix: v
    use-tag: true
    tag-filter: v4.3.
