package:
  name: kube-bench
  version: 0.6.18
  epoch: 0
  description: Checks whether Kubernetes is deployed according to security best practices as defined in the CIS Kubernetes Benchmark
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - kubectl

environment:
  contents:
    packages:
      - wolfi-baselayout
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aquasecurity/kube-bench
      tag: v${{package.version}}
      expected-commit: 18f8456abdaebd58cafeb90071ca27e3ffee2179

  - uses: go/build
    with:
      modroot: .
      packages: .
      output: kube-bench
      deps: github.com/docker/distribution@v2.8.2
      ldflags: |
        -s -w
        -X github.com/aquasecurity/kube-bench/cmd.cfgDir=/etc/kube-bench/cfg
        -X github.com/aquasecurity/kube-bench/cmd.KubeBenchVersion=v${{package.version}}

subpackages:
  - name: "kube-bench-configs"
    description: "Configuration files for kube-bench"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/etc/kube-bench/cfg
          cp -rv ./cfg/* ${{targets.subpkgdir}}/etc/kube-bench/cfg

update:
  enabled: true
  github:
    identifier: aquasecurity/kube-bench
    strip-prefix: v
    use-tag: true
    tag-filter: v
