package:
  name: kubernetes-csi-external-snapshotter
  version: 6.3.0
  epoch: 3
  description: Sidecar container that watches Kubernetes Snapshot CRD objects and triggers CreateSnapshot/DeleteSnapshot against a CSI endpoint
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - wolfi-baselayout
      - busybox
      - build-base
      - go
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-csi/external-snapshotter
      tag: v${{package.version}}
      expected-commit: a6ac2ee3b6f48d1c05548d3f2201dd493ac14134

  - runs: |
      # CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod vendor

      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      install -Dm755 ./bin/csi-snapshotter ${{targets.destdir}}/usr/bin/csi-snapshotter

  - uses: strip

subpackages:
  - name: kubernetes-csi-external-snapshot-controller
    pipeline:
      - runs: |
          mkdir -p ${{targets.destdir}}/usr/bin
          install -Dm755 ./bin/snapshot-controller ${{targets.subpkgdir}}/usr/bin/snapshot-controller

  - name: kubernetes-csi-external-snapshot-validation-webhook
    pipeline:
      - runs: |
          mkdir -p ${{targets.destdir}}/usr/bin
          install -Dm755 ./bin/snapshot-validation-webhook ${{targets.subpkgdir}}/usr/bin/snapshot-validation-webhook

update:
  enabled: true
  github:
    identifier: kubernetes-csi/external-snapshotter
    strip-prefix: v
    use-tag: true
    tag-filter: v
