package:
  name: kubernetes-csi-livenessprobe
  version: 2.11.0
  epoch: 3
  description: A sidecar container that can be included in a CSI plugin pod to enable integration with Kubernetes Liveness Probe.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-csi/livenessprobe
      tag: v${{package.version}}
      expected-commit: 33ea6c01f303d03e7e493e8e4622c08ce11722b8

  - uses: go/build
    with:
      packages: ./cmd/livenessprobe
      ldflags: "-s -w -X main.version=v${{package.version}} -extldflags '-static'"
      vendor: "true"
      output: livenessprobe
      # CVE-2023-39325 and CVE-2023-3978
      deps: golang.org/x/net@v0.17.0

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-csi/livenessprobe
    strip-prefix: v
