package:
  name: kubernetes-csi-external-provisioner
  version: 3.6.0
  epoch: 3
  description: A dynamic provisioner for Kubernetes CSI plugins.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - build-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-csi/external-provisioner
      expected-commit: 4b69bc58565d5282c762570f008caf378d8a5301
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: ./cmd/csi-provisioner
      output: csi-provisioner
      ldflags: -s -w -X main.version=${{package.version}}
      # CVE-2023-39325 and CVE-2023-3978
      deps: golang.org/x/net@v0.17.0
      vendor: "true"

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-csi/external-provisioner
    strip-prefix: v
