package:
  name: kubevela
  version: 1.9.6
  epoch: 4
  description: KubeVela is a modern application delivery platform that makes deploying and operating applications across today's hybrid, multi-cloud environments easier, faster and more reliable
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go
      - build-base

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/kubevela/kubevela/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: 8b332d8cf4593d9da2502a03aca2437725011503f6cbf06fd76ce7a9ac052eb3

  - runs: |
      export CGO_ENABLED=0
      export GO111MODULE=on

  - uses: go/build
    with:
      packages: ./cmd/core/main.go
      ldflags: -s -w -X github.com/oam-dev/kubevela/version.VelaVersion=${{package.version}}
      output: manager
      # Mitigate CVE-2023-39325, CVE-2023-3978, CVE-2023-44487
      deps: golang.org/x/net@v0.17.0

  - uses: go/build
    with:
      packages: ./references/cmd/cli/main.go
      ldflags: -s -w -X github.com/oam-dev/kubevela/version.VelaVersion=${{package.version}}
      output: vela

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubevela/kubevela
    strip-prefix: v
