package:
  name: kubernetes-dns-node-cache
  version: 1.22.20
  epoch: 5
  description: NodeLocal DNSCache improves Cluster DNS performance by running a DNS caching agent on cluster nodes as a DaemonSet.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - wolfi-baselayout
      - build-base
      - ca-certificates-bundle
      - busybox
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes/dns
      tag: ${{package.version}}
      expected-commit: 7bcdf8411514fd4e22de11e93f33559c7304ed21

  - runs: |
      # Mitigate GHSA-xc8m-28vv-4pjc, GHSA-cgcv-5272-97pr, GHSA-qc2g-gmh6-95p4
      go get k8s.io/kubernetes@v1.24.15
      # CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0

      go mod tidy
      go mod vendor

  - uses: go/build
    with:
      packages: ./cmd/node-cache
      output: node-cache
      ldflags: -s -w -X github.com/kubernetes/dns/pkg/version.Version=v${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    strip-prefix: v
    identifier: kubernetes/dns
    tag-filter: v
    use-tag: true
