package:
  name: kyverno-policy-reporter-kyverno-plugin
  version: 1.6.0
  epoch: 0
  description: Policy Reporter Kyverno Plugin
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kyverno/policy-reporter-kyverno-plugin
      tag: v${{package.version}}
      expected-commit: 41fb7e56e9f1d3be3bf6406213524b6465f0be6f

  - uses: go/build
    with:
      modroot: .
      packages: .
      # Mitigate CVE-2023-39325, CVE-2023-3978, CVE-2023-44487
      deps: golang.org/x/net@v0.17.0
      output: kyverno-plugin
      ldflags: -w

  - runs: |
      mkdir -p ${{targets.destdir}}/app/templates
      cp -R ./templates ${{targets.destdir}}/app/templates

  - uses: strip

subpackages:
  - name: kyverno-policy-reporter-kyverno-plugin-compat
    description: compatibility symlinks package for kyverno-plugin Dockerfile
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /app/
          mkdir -p ${{targets.subpkgdir}}/app
          ln -sf /usr/bin/kyverno-plugin ${{targets.subpkgdir}}/app/kyverno-plugin

update:
  enabled: true
  github:
    identifier: kyverno/policy-reporter-kyverno-plugin
    use-tag: true
    strip-prefix: v
