package:
  name: kyverno-policy-reporter-ui
  version: 1.9.0
  epoch: 0
  description: Policy Reporter UI
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - wolfi-baselayout
      - busybox
      - build-base
      - ca-certificates-bundle
      - curl
      - bash
      - git
      - nodejs-16
      - python-3.11
      - openssl
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kyverno/policy-reporter-ui
      tag: v${{package.version}}
      expected-commit: 3c8ba6f2d00bee796dc49d13f1748c6760b8af99

  - runs: |
      export NODE_OPTIONS=--openssl-legacy-provider
      npm install
      npm run generate

      mkdir -p ${{targets.destdir}}/app
      cp -R ./dist ${{targets.destdir}}/app/dist

  - uses: go/build
    with:
      modroot: server
      packages: .
      # Mitigate CVE-2023-39325, CVE-2023-44487
      deps: golang.org/x/net@v0.17.0
      output: policyreporter-ui
      ldflags: -w

  - uses: strip

subpackages:
  - name: kyverno-policy-reporter-ui-compat
    description: compatibility symlinks package for policyreporter-ui Dockerfile
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /app/
          mkdir -p ${{targets.subpkgdir}}/app
          ln -sf /usr/bin/policyreporter-ui ${{targets.subpkgdir}}/app/policyreporter-ui

update:
  enabled: true
  github:
    identifier: kyverno/policy-reporter-ui
    use-tag: true
    strip-prefix: v
