package:
  name: liblbfgs
  version: 1.10
  epoch: 0
  description: A library of Limited-memory Broyden-Fletcher-Goldfarb-Shanno (L-BFGS)
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - libtool
      - m4

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/chokkan/liblbfgs/archive/v${{package.version}}.tar.gz
      expected-sha256: 95c1997e6c215c58738f5f723ca225d64c8070056081a23d636160ff2169bd2f

  - uses: patch
    with:
      patches: disable-sse2.patch

  - runs: autoupdate

  - runs: ./autogen.sh

  - runs: autoreconf -vif

  - uses: autoconf/configure
    with:
      opts: |
        --disable-sse2

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "liblbfgs-dev"
    description: "headers for liblbfgs"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - liblbfgs

update:
  enabled: false
