package:
  name: llhttp
  version: 8.1.1
  epoch: 0
  description: "HTTP parser written against llparse"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - build-base
      - cmake
      - clang-16
      - nodejs-lts
      - npm

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/nodejs/llhttp/archive/v${{package.version}}/llhttp-${{package.version}}.tar.gz
      expected-sha512: 18530d1fcfde13ba634b367852e53bf7a2dc0eb130f07fbbb5b5e02b3d4ff0ab0cd7c5a0adef8a7a0e93a0104a2544ce11d3631792539c48e1a918c5d40f7f3c

  - uses: patch
    with:
      patches: fix-sed.patch

  - runs: |
      npm ci

  - runs: |
      make release RELEASE="${{package.version}}"
      cmake -S release -B releasebuild \
        -DCMAKE_BUILD_TYPE=MinSizeRel \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DBUILD_SHARED_LIBS=ON
      cmake --build releasebuild

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install releasebuild

  - uses: strip

subpackages:
  - name: "llhttp-dev"
    description: "llhttp development headers"
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: nodejs/llhttp
    strip-prefix: release/v
    tag-filter: release/
