package:
  name: llvm-cmake-17
  version: 17.0.3
  epoch: 0
  description: CMake macros for LLVM build system, version 17
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - cmake

environment:
  contents:
    packages:
      - busybox

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+).*
    replace: $1
    to: major-version

pipeline:
  - working-directory: ${{targets.destdir}}/usr/lib/llvm${{vars.major-version}}/share/cmake
    uses: fetch
    with:
      uri: https://github.com/llvm/llvm-project/releases/download/llvmorg-${{package.version}}/cmake-${{package.version}}.src.tar.xz
      expected-sha256: 54fc534f0da09088adbaa6c3bfc9899a500153b96e60c2fb9322a7aa37b1027a
      delete: true

update:
  enabled: true
  github:
    identifier: llvm/llvm-project
    strip-prefix: llvmorg-
    tag-filter: llvmorg-17
    use-tag: true
