package:
  name: llvm-libcxx-17
  version: 17.0.3
  epoch: 0
  description: The LLVM libc++ libraries
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - llvm-libcxx=17

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - cmake
      - samurai
      - git
      - python3
      - curl
      - clang
      - libstdc++-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/llvm/llvm-project
      tag: llvmorg-${{package.version}}
      expected-commit: 888437e1b60011b8a375dd30928ec925b448da57

  - runs: |
      gccver=$(gcc -dumpversion)
      CC=clang CXX=clang cmake -G Ninja -S runtimes -B build \
        -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi" \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DLLVM_INCLUDE_TESTS=OFF \
        -DLIBCXX_INCLUDE_BENCHMARKS=OFF \
        -DLIBCXX_CXX_ABI=libstdc++ \
        -DLLVM_BUILD_LLVM_DYLIB=ON \
        -DLIBCXX_CXX_ABI_INCLUDE_PATHS=/usr/include/c++/$gccver/

  - runs: |
      cmake --build build

  - runs: |
      DESTDIR=${{targets.destdir}} cmake --install build

  - uses: strip

subpackages:
  - name: llvm-libcxx-17-dev
    pipeline:
      - uses: split/dev
    dependencies:
      provides:
        - llvm-libcxx-dev=17

  - name: llvm-libcxxabi-17
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv ${{targets.destdir}}/usr/lib/libc++abi.so* ${{targets.subpkgdir}}/usr/lib/
    dependencies:
      provides:
        - llvm-libcxxabi=17

update:
  enabled: true
  github:
    identifier: llvm/llvm-project
    use-tag: true
    tag-filter: llvmorg-17.
    strip-prefix: llvmorg-
