package:
  name: loki
  version: 2.9.2
  epoch: 0
  description: Like Prometheus, but for logs.
  copyright:
    - license: AGPL-3.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grafana/loki
      tag: v${{package.version}}
      expected-commit: a17308db6f24874a789bacb4b441b26831d638b5

  - uses: autoconf/make

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      mv cmd/loki/loki ${{targets.destdir}}/usr/bin/loki

      # Add the default config
      mkdir -p ${{targets.destdir}}/etc/loki
      mv local-config.yaml ${{targets.destdir}}/etc/loki

  - uses: strip

subpackages:
  - name: logcli
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv cmd/logcli/logcli ${{targets.subpkgdir}}/usr/bin/logcli

  - name: promtail
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv clients/cmd/promtail/promtail ${{targets.subpkgdir}}/usr/bin/promtail

          mkdir -p ${{targets.subpkgdir}}/etc/promtail
          mv promtail-local-config.yaml ${{targets.subpkgdir}}/etc/promtail/config.yml

  - name: loki-canary
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv cmd/loki-canary/loki-canary ${{targets.subpkgdir}}/usr/bin/loki-canary

update:
  enabled: true
  github:
    identifier: grafana/loki
    strip-prefix: v
    use-tag: true
    tag-filter: v
