package:
  name: mc
  # minio uses strange versioning, the upstream version is RELEASE.2023-03-23T20-03-04Z
  # when bumping this, also bump the tag in git-checkout below
  version: 0.20230628.215417
  epoch: 7
  description: Multi-Cloud Object Storage
  copyright:
    - license: AGPL-3.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - build-base
      - perl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/minio/mc
      tag: RELEASE.2023-06-28T21-54-17Z
      expected-commit: eebdcdf36501cec35c893d7e8ab7a7473ff6860a

  - runs: |
      # fix CVE-2023-39325 and CVE-2023-3978.
      go get golang.org/x/net@v0.17.0
      go mod tidy
      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      mv mc ${{targets.destdir}}/usr/bin

  - uses: strip

update:
  enabled: false # odd versions which cannot be compared and automated
