package:
  name: memcached-exporter
  version: 0.13.0
  epoch: 7
  description: Exports metrics from memcached servers for consumption by Prometheus.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - go
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/prometheus/memcached_exporter/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: bf8384f4cea5066a6492fdded2b0bef35859407363c20e2788b220373f09951c

  - uses: go/build
    with:
      packages: ./cmd/memcached_exporter
      output: memcached_exporter
      ldflags: -s -w
      # CVE-2023-39325 and CVE-2023-3978
      deps: golang.org/x/net@v0.17.0

  - uses: strip

update:
  enabled: true
  github:
    identifier: prometheus/memcached_exporter
    strip-prefix: v
