package:
  name: meson
  version: 1.2.2
  epoch: 2
  description: Fast and user friendly build system
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - python3
      - samurai

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - samurai

pipeline:
  - uses: fetch
    with:
      expected-sha256: 4a0f04de331fbc7af3b802a844fc8838f4ccd1ded1e792ba4f8f2faf8c5fe4d6
      uri: https://github.com/mesonbuild/meson/releases/download/${{package.version}}/meson-${{package.version}}.tar.gz

  - runs: python3 setup.py build

  - runs: python3 setup.py install --prefix=/usr --root=${{targets.destdir}}

subpackages:
  - name: meson-doc
    pipeline:
      - uses: split/manpages
    description: meson manpages

update:
  enabled: true
  release-monitor:
    identifier: 6472
