package:
  name: minio
  # minio uses strange versioning, the upstream version is RELEASE.2023-09-04T19-57-37Z
  # when bumping this, also bump the tag in git-checkout below
  version: 0.20230904.195737
  epoch: 5
  description: Multi-Cloud Object Storage
  copyright:
    - license: AGPL-3.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - build-base
      - perl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/minio/minio
      tag: RELEASE.2023-09-04T19-57-37Z
      expected-commit: 1c99fb106c3e1448ed92f8465d5695d055d432e7

  - runs: |
      # Mitigate CVE-2023-39325, CVE-2023-3978, CVE-2023-44487
      go get golang.org/x/net@v0.17.0
      go mod tidy

      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      mv minio ${{targets.destdir}}/usr/bin

  - uses: strip

update:
  enabled: false # uses strange versioning
