package:
  name: mold
  version: 2.3.0
  epoch: 0
  description: "mold linker"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - wolfi-baselayout
      - busybox
      - ca-certificates-bundle
      - build-base
      - cmake
      - samurai
      - mimalloc2-dev
      - openssl-dev
      - libtbb-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/rui314/mold/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: 6cfc1af0214f993be1b0ae4a2f0278d32b7fc48155c15b2d03758f6d81e7250b

  - name: 'Configure mold'
    runs: |
      cmake -B build -G Ninja \
        -DCMAKE_C_COMPILER=gcc \
        -DCMAKE_CXX_COMPILER=g++ \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DMOLD_LTO=ON \
        -DMOLD_USE_SYSTEM_MIMALLOC=ON \
        -DMOLD_USE_SYSTEM_TBB=ON \
        -DBUILD_TESTING="OFF"

  - runs: |
      cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

  - name: 'Clean up documentation'
    runs: |
      rm -rf ${{targets.destdir}}/usr/share/info

  - uses: strip

update:
  enabled: true
  github:
    identifier: rui314/mold
    strip-prefix: v
