package:
  name: mozjs91
  version: 91.13.0
  epoch: 1
  description:
  copyright:
    - license: MPL-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - python-3.10
      - curl
      - rust
      - clang-15
      - llvm15
      - llvm-lld
      - llvm15-tools
      - m4
      - erlang-dev
      - jemalloc-dev
      - perl
      - zlib-dev
      - icu-dev
      - icu
      - readline-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 53be2bcde0b5ee3ec106bd8ba06b8ae95e7d489c484e881dfbe5360e4c920762
      uri: https://ftp.mozilla.org/pub/firefox/releases/${{package.version}}esr/source/firefox-${{package.version}}esr.source.tar.xz

  - runs: |
      cat > .mozconfig <<- END
      ac_add_options --enable-project=js
      mk_add_options MOZ_OBJDIR='${PWD}'/obj
      ac_add_options --prefix=/usr
      ac_add_options --enable-release
      ac_add_options --enable-hardening
      ac_add_options --enable-optimize
      ac_add_options --enable-linker=lld
      ac_add_options --disable-bootstrap
      ac_add_options --disable-debug
      ac_add_options --disable-debug-symbols
      ac_add_options --disable-strip

      # System libraries
      ac_add_options --with-system-icu
      ac_add_options --with-system-zlib

      # Features
      ac_add_options --enable-readline
      ac_add_options --enable-shared-js
      ac_add_options --enable-tests
      ac_add_options --with-intl-api
      END

      # disable rust-simd on aarch64
      if [ "${{build.arch}}" = "aarch64" ]; then
        echo "ac_add_options --disable-rust-simd" >> .mozconfig
      fi

      # This build requires 3.10, but symlinked into python3
      ln -s /usr/bin/python3.10 /usr/bin/python3

      export MACH_USE_SYSTEM_PYTHON=1
      export MOZ_NOSPAM=1

      ./mach build


      cd obj
      make DESTDIR=${{targets.destdir}} install

      rm -f "${{targets.destdir}}"/usr/lib/*.ajs

  - uses: strip

subpackages:
  - name: mozjs91-dev
    pipeline:
      - uses: split/dev

update:
  enabled: true
  release-monitor:
    identifier: 369151
