package:
  name: netcat-openbsd
  version: "1.226"
  epoch: 0
  description: The TCP/IP swiss army knife. OpenBSD variant from debian.
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - patch
      - libbsd-dev
      - libmd-dev

pipeline:
  - uses: fetch
    with:
      uri: https://deb.debian.org/debian/pool/main/n/netcat-openbsd/netcat-openbsd_${{package.version}}.orig.tar.gz
      expected-sha512: 1826086282236233757983619d423a538c253474e82050a55963bbc14f8d343432704e9748259873dcab75af03a708d2e2c05b3752e44bd2d198662f8dd5cd3a

  - uses: fetch
    with:
      uri: http://deb.debian.org/debian/pool/main/n/netcat-openbsd/netcat-openbsd_${{package.version}}-1.debian.tar.xz
      expected-sha512: b7ab1a133cbfcca37864df4b2cc5b8d5fab25104670fb03a6ead538c6433064c736ec7c25b930a2c3ea28e19dc8279130f4465607174f1a4806b8d2f94596e74
      extract: false
      delete: false

  - runs: |
      mkdir -p debian
      tar -x '--strip-components=1' -f "netcat-openbsd_${{package.version}}-1.debian.tar.xz" -C debian
      while read -r patch; do
        patch -Np1 < ./debian/patches/"$patch"
      done < ./debian/patches/series

      # linux port requires b64_ntop. include in in SRCS (Makefile)
      # we also want this to link with libmd as well because it uses sha512update...
      sed -i Makefile -e "/SRCS=/s;\(.*\);& base64.c;"
      sed -i Makefile -e "s/\libbsd\b/& libmd/"

  - runs: |
      make CFLAGS="$CFLAGS -DDEBIAN_VERSION=\"\\\"${{package.version}}\\\"\""

  - runs: |
      install -Dm755 nc "${{targets.destdir}}"/usr/bin/nc
      install -Dm644 nc.1 "${{targets.destdir}}"/usr/share/man/man1/nc.openbsd.1

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 21534
