package:
  name: newrelic-infrastructure-agent
  version: 1.47.2
  epoch: 3
  description: New Relic Infrastructure Agent
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - wolfi-baselayout
      - busybox
      - build-base
      - go
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/infrastructure-agent
      tag: ${{package.version}}
      expected-commit: 9b48d5394edc7b657c6c29817e0d095cc2547ec6

  - runs: |
      # Our global LDFLAGS conflict with a Makefile parameter: https://github.com/newrelic/infrastructure-agent/blob/07ab68f181e25a1552588a3953167e0b15f52372/build/build.mk#L20-L22
      unset LDFLAGS

      # Mitigate CVE-2023-39325, CVE-2023-3978, CVE-2023-44487
      go get golang.org/x/net@v0.17.0
      go mod tidy

      GOOS=$(go env GOOS) GOARCH=$(go env GOARCH)

      make OS=linux GOARCH=${GOARCH} compile
      make OS=linux GOARCH=${GOARCH} dist

      mkdir -p ${{targets.destdir}}/usr/bin

      install -m755 -D ./dist/${GOOS}-newrelic-infra_${GOOS}_${GOARCH}/newrelic-infra "${{targets.destdir}}"/usr/bin/newrelic-infra
      install -m755 -D ./dist/${GOOS}-newrelic-infra-service_${GOOS}_${GOARCH}/newrelic-infra-service "${{targets.destdir}}"/usr/bin/newrelic-infra-service
      install -m755 -D ./dist/${GOOS}-newrelic-infra-ctl_${GOOS}_${GOARCH}/newrelic-infra-ctl "${{targets.destdir}}"/usr/bin/newrelic-infra-ctl

  - uses: strip

update:
  enabled: true
  github:
    identifier: newrelic/infrastructure-agent
