package:
  name: newrelic-infra-operator
  version: 0.11.2
  epoch: 1
  description: Newrelic kubernetes operator of infrastructure
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go
      - build-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/newrelic-infra-operator
      tag: v${{package.version}}
      expected-commit: 0e9674e331e7acf2eca697bd509058e23e13cb4f

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      mv newrelic-infra-operator ${{targets.destdir}}/usr/bin/newrelic-infra-operator

  - uses: strip

update:
  enabled: true
  github:
    identifier: newrelic/newrelic-infra-operator
    strip-prefix: v
    tag-filter: v
    use-tag: true
