package:
  name: newrelic-nri-kube-events
  version: 2.2.12
  epoch: 1
  description: New Relic integration that forwards Kubernetes events to New Relic
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - wolfi-baselayout
      - busybox
      - build-base
      - go
      - ca-certificates-bundle

pipeline:
  # We can't use go/install because this requires specific ldflags to set the version
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-kube-events
      tag: v${{package.version}}
      expected-commit: 3c6dbdd727491d8c73b7057c043c9de924e4ffd6

  - uses: go/build
    with:
      packages: ./cmd/nri-kube-events
      ldflags: -s -w -X main.integrationVersion=v${{ package.version }}
      output: nri-kube-events

  - uses: strip

update:
  enabled: true
  github:
    identifier: newrelic/nri-kube-events
    strip-prefix: v
    use-tag: true
    tag-filter: v
