package:
  name: nodetaint
  version: 0.0.4
  epoch: 6
  description: Controller to manage taints for nodes in a k8s cluster.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/wish/nodetaint
      tag: v${{package.version}}
      expected-commit: 9f648717bd31a782696335450ee05a5ed79cd870

  - runs: |
      # Mitigate  GHSA-3vm4-22fp-5rfm, GHSA-gwc9-m7rh-j2ww and GHSA-8c26-wmh5-6g9v
      go get golang.org/x/crypto@1baeb1ce4c0b

      # Mitigate GHSA-vvpx-j8f3-3w6h and GHSA-69ch-w2m2-3vjp
      go get golang.org/x/text@v0.3.8

      # GHSA-8cfg-vx93-jvxw
      go get k8s.io/client-go@v0.20.0-alpha.2

      # Mitigate CVE-2023-39325, CVE-2023-3978, CVE-2023-44487
      go get golang.org/x/net@v0.17.0

      go mod tidy -compat=1.17

      CGO_ENABLED=0 GOARCH=$(go env GOARCH) GOOS=$(go env GOOS) go build -o . -a -installsuffix cgo .
      mkdir -p ${{targets.destdir}}/usr/bin
      install -Dm755 nodetaint ${{targets.destdir}}/usr/bin/nodetaint

  - uses: strip

update:
  enabled: true
  github:
    identifier: wish/nodetaint
    strip-prefix: v
    use-tag: true
    tag-filter: v
