package:
  name: nri-kubernetes
  version: 3.18.2
  epoch: 1
  description: New Relic integration for Kubernetes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go
      - build-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-kubernetes
      tag: v${{package.version}}
      expected-commit: e1ade4c9dac38c5de06006bc1e2bb22493fda9ad

  - runs: |
      # Our global LDFLAGS conflict with a Makefile parameter
      unset LDFLAGS
      make compile
      mkdir -p ${{targets.destdir}}/usr/bin
      mv bin/nri-kubernetes ${{targets.destdir}}/usr/bin/nri-kubernetes

  - uses: strip

update:
  enabled: true
  github:
    identifier: newrelic/nri-kubernetes
    strip-prefix: v
    tag-filter: v
    use-tag: true
