package:
  name: nvidia-device-plugin
  version: 0.14.1
  epoch: 5
  description: NVIDIA device plugin for Kubernetes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/NVIDIA/k8s-device-plugin
      tag: v${{package.version}}
      expected-commit: 7086f91dfcd0cd7b06863be4a315ba873f0b81f9

  - runs: |
      # Mitigate CVE-2023-39325, CVE-2023-3978, CVE-2023-44487
      go get golang.org/x/net@v0.17.0
      go mod tidy
      go mod vendor

      make
      mkdir -p ${{targets.destdir}}/usr/bin
      mv config-manager ${{targets.destdir}}/usr/bin/
      mv nvidia-device-plugin ${{targets.destdir}}/usr/bin/

update:
  enabled: true
  github:
    identifier: NVIDIA/k8s-device-plugin
    strip-prefix: v
    tag-filter: v
