package:
  name: ollama
  version: 0.1.3
  epoch: 0
  description: Get up and running with Llama 2 and other large language models locally
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - build-base
      - go
      - cmake

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jmorganca/ollama
      tag: v${{package.version}}
      expected-commit: 832b4db9d4baf22497145dde55f334b292ed665f

  - runs: |
      go generate ./...
      CGO_ENABLED=1 go build -ldflags '-linkmode external -extldflags "-static"' .
      mkdir -p ${{targets.destdir}}/usr/bin
      mv ollama ${{targets.destdir}}/usr/bin

  - uses: strip

update:
  enabled: true
  github:
    identifier: jmorganca/ollama
    strip-prefix: v
    tag-filter: v
    use-tag: true
