package:
  name: oniguruma
  version: 6.9.9
  epoch: 0
  description: "a regular expressions library"
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - libtool

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/kkos/oniguruma/archive/v${{package.version}}.tar.gz
      expected-sha256: 001aa1202e78448f4c0bf1a48c76e556876b36f16d92ce3207eccfd61d99f2a0

  - name: Run autoreconf
    runs: |
      autoreconf -vfi

  - uses: autoconf/configure
    with:
      opts: --enable-posix-api

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "oniguruma-dev"
    description: "oniguruma headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - oniguruma

update:
  enabled: true
  release-monitor:
    identifier: 11184
