package:
  name: opentofu
  version: 1.6.0_alpha2
  epoch: 0
  copyright:
    - license: MPL-2.0

environment:
  environment:
    CGO_ENABLED: 0

var-transforms:
  - from: ${{package.version}}
    match: '_'
    replace: '-'
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/opentofu/opentofu
      tag: v${{vars.mangled-package-version}}
      expected-commit: 9e6bc7f86f1cbf36bc8dc079b97273fbd7909117

  - uses: go/build
    with:
      modroot: .
      packages: ./cmd/tofu
      output: tofu
      ldflags: -s -w
      # Mitigate CVE-2023-39325, CVE-2023-3978, CVE-2023-44487
      deps: golang.org/x/net@v0.17.0

  - uses: strip

subpackages:
  - name: opentofu-compat
    description: Compat package for opentofu
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          ln -s /usr/bin/opentofu "${{targets.subpkgdir}}"/usr/local/bin

  - name: opentofu-local-provider-config
    description: Configure opentofu to use local providers
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/opentofu/provider-mirror
          cat > "${{targets.subpkgdir}}"/opentofu/.opentofurc <<EOF
          provider_installation {
            filesystem_mirror {
              path    = "/opentofu/provider-mirror"
              include = ["*/*"]
            }
            direct {
              exclude = ["*/*"]
            }
          }
          EOF

update:
  enabled: true
  github:
    identifier: opentofu/opentofu
    strip-prefix: v
    use-tag: true
    tag-filter: v
