package:
  name: pax-utils
  version: 1.3.7
  epoch: 1
  description: "ELF related utilities for 32-bit and 64-bit binaries"
  copyright:
    - license: GPL-2.0-only
  dependencies:
    runtime:
      - scanelf

environment:
  contents:
    packages:
      - wolfi-baselayout
      - busybox
      - ca-certificates-bundle
      - build-base
      - xz

pipeline:
  - uses: fetch
    with:
      uri: https://gitweb.gentoo.org/proj/pax-utils.git/snapshot/pax-utils-${{package.version}}.tar.gz
      expected-sha256: 9b5e7d7da71210b47aa3ccdf026bbbcc5d5cf8321be2285ee1ddcb0a761fc7cb

  - runs: |
      make -j$(nproc) USE_CAP=no CC="${{host.triplet.gnu}}-gcc"

  - uses: autoconf/make-install

  - runs: |
      rm -f "${{targets.destdir}}"/usr/bin/lddtree

subpackages:
  - name: "scanelf"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/scanelf "${{targets.subpkgdir}}"/usr/bin/scanelf

update:
  enabled: true
  release-monitor:
    identifier: 2601
