package:
  name: pnpm
  version: 8.9.2
  epoch: 0
  description: "Fast, disk space efficient package manager"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - wolfi-base
      - build-base
      - nodejs-18
      - ca-certificates-bundle
      - curl
      - git
      - npm
      - gcc-12
      - make
      - automake
      - autoconf
      - pnpm
      - python3

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pnpm/pnpm
      tag: v${{package.version}}
      expected-commit: 7daf0be5d1e7cf6d2bac816f47e2f63527699f1d

  - runs: |
      /usr/bin/pnpm install
      /usr/bin/pnpm run compile
      mkdir -p "${{targets.destdir}}"/usr/lib/node_modules/pnpm
      mkdir -p "${{targets.destdir}}"/usr/bin/
      cd pnpm

      ln -sf /usr/lib/node_modules/pnpm/bin/pnpm.cjs  "${{targets.destdir}}"/usr/bin/pnpm
      ln -sf /usr/lib/node_modules/pnpm/bin/pnpx.cjs  "${{targets.destdir}}"/usr/bin/pnpx
      mv bin  "${{targets.destdir}}"/usr/lib/node_modules/pnpm
      mv dist "${{targets.destdir}}"/usr/lib/node_modules/pnpm

update:
  enabled: true
  github:
    identifier: pnpm/pnpm
    strip-prefix: v
    tag-filter: v
