package:
  name: prometheus-elasticsearch-exporter
  version: 1.6.0
  epoch: 7
  description: Elasticsearch stats exporter for Prometheus
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - bash
      - build-base
      - go
      - curl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus-community/elasticsearch_exporter
      tag: v${{package.version}}
      expected-commit: a5f42797a10de8229eb5544c25c092f2fece5b63

  - runs: |
      # Handle CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy

      make common-build

  - runs: |
      install -Dm755 elasticsearch_exporter "${{targets.destdir}}"/usr/bin/elasticsearch_exporter

  - uses: strip

subpackages:
  - name: prometheus-elasticsearch-exporter-bitnami-compat
    description: "compat package with bitnami/elasticsearch-exporter image"
    pipeline:
      - uses: bitnami/compat
        with:
          image: elasticsearch-exporter
          version-path: 1/debian-11
      - runs: |
          mkdir -p ${{targets.contextdir}}/opt/bitnami/elasticsearch-exporter/bin
          ln -s /usr/bin/elasticsearch_exporter ${{targets.contextdir}}/opt/bitnami/elasticsearch-exporter/bin/elasticsearch_exporter

update:
  enabled: true
  github:
    identifier: prometheus-community/elasticsearch_exporter
    strip-prefix: v
    use-tag: true
