package:
  name: prometheus-adapter
  version: 0.11.1
  epoch: 3
  description: Prometheus Adapter for Kubernetes Metrics APIs
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - go
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/prometheus-adapter
      expected-commit: 4cc5de93cbaabdb273c50c7d8a28378981938326
      tag: v${{package.version}}

  - runs: |
      # Handle CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy

      make prometheus-adapter

  - runs: |
      install -Dm755 adapter "${{targets.destdir}}"/usr/bin/adapter

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/prometheus-adapter
    strip-prefix: v
