package:
  name: prometheus-mongodb-exporter
  version: 0.39.0
  epoch: 4
  description: A Prometheus exporter for MongoDB including sharding, replication and storage engines
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/percona/mongodb_exporter
      expected-commit: 430098a28613273e386563a84c57b9e84dc1a298
      tag: v${{package.version}}

  - runs: |
      # Handle CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0

      # Patch GHSA-7rg2-cxvp-9p7p
      go get github.com/prometheus/exporter-toolkit@v0.7.3
      go mod tidy

      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      mv mongodb_exporter ${{targets.destdir}}/usr/bin/

  - uses: strip

subpackages:
  - name: prometheus-mongodb-exporter-bitnami-compat
    description: "compat package with bitnami/mongodb helm chart"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/bin
          ln -s /usr/bin/mongodb_exporter "${{targets.subpkgdir}}"/bin/mongodb_exporter

update:
  enabled: true
  github:
    identifier: percona/mongodb_exporter
    strip-prefix: v
