package:
  name: prometheus-statsd-exporter
  version: 0.24.0
  epoch: 3
  description: StatsD exporter for Prometheus
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - wolfi-base
      - go
      - curl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/statsd_exporter
      expected-commit: e91ce201d50556b1ccf21c484c4b93c3b10a3442
      tag: v${{package.version}}

  - runs: |
      # Handle CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy

      make common-build

  - runs: |
      install -Dm755 statsd_exporter "${{targets.destdir}}"/usr/bin/statsd_exporter

  - uses: strip

update:
  enabled: true
  github:
    identifier: prometheus/statsd_exporter
    strip-prefix: v
