package:
  name: prometheus-alertmanager
  # When bumping this version you can remove the `go get` line in the build script
  version: 0.26.0
  epoch: 4
  description: Prometheus Alertmanager
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - bash
      - build-base
      - go
      - curl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/alertmanager
      tag: v${{package.version}}
      expected-commit: d7b4f0c7322e7151d6e3b1e31cbc15361e295d8d

  - runs: |
      # Handle CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy

      make build

  - runs: |
      install -Dm755 amtool "${{targets.destdir}}"/usr/bin/amtool
      install -Dm755 alertmanager "${{targets.destdir}}"/usr/bin/alertmanager
      install -Dm644 examples/ha/alertmanager.yml "${{targets.destdir}}"/etc/alertmanager/alertmanager.yml

  - uses: strip

update:
  enabled: true
  github:
    identifier: prometheus/alertmanager
    strip-prefix: v
