package:
  name: prometheus-postgres-exporter
  version: 0.14.0
  epoch: 3
  description: Prometheus Exporter for Postgres server metrics
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - bash
      - build-base
      - go
      - curl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus-community/postgres_exporter
      tag: v${{package.version}}
      expected-commit: c06e57db4e502696ab4e8b8898bb2a59b7b33a59

  - runs: |
      # Handle CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy

      make build

  - runs: |
      install -Dm755 postgres_exporter "${{targets.destdir}}"/usr/bin/postgres_exporter

  - uses: strip

update:
  enabled: true
  github:
    identifier: prometheus-community/postgres_exporter
    strip-prefix: v
