package:
  name: pulumi-language-yaml
  version: 1.3.0
  epoch: 5
  description: Pulumi Language SDK for YAML
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - go
      - busybox
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pulumi/pulumi-yaml.git
      tag: v${{package.version}}
      destination: ${{package.name}}
      expected-commit: 2135f7eeef902fe4ee3cf52f049b8f9f42ef3db5

  - working-directory: ${{package.name}}
    pipeline:
      - runs: |
          set -x
          # Mitigate CVE-2023-39325 and CVE-2023-3978
          go get golang.org/x/net@v0.17.0
          go mod tidy

          export CGO_ENABLED=0 GO111MODULE=on
          go build \
            -o "${{targets.destdir}}/usr/bin/pulumi-language-yaml" \
            -ldflags="-s -w -X github.com/pulumi/pulumi-yaml/pkg/version.Version=v${{package.version}}" \
            ./cmd/pulumi-language-yaml/
      - uses: strip

update:
  enabled: true
  github:
    identifier: pulumi/pulumi-yaml
    strip-prefix: v
