package:
  name: pulumi
  # When this version is bumped, please check the dependency version
  # patches below and remove if possible.
  version: 3.89.0
  epoch: 1
  description: Infrastructure as Code in any programming language
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - nodejs
      - patch
      - python3
      - python3-dev
      - yarn
  environment:
    CGO_ENABLED: "0"
    GO111MODULE: "on"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pulumi/pulumi.git
      tag: v${{package.version}}
      destination: ${{package.name}}
      expected-commit: 963a17b094ac1013d4ffdab6bc765a5ed87998b6

  - working-directory: ${{package.name}}
    pipeline:
      - runs: |
          for d in pkg sdk; do
            (
              cd $d

              # CVE-2023-39325 and CVE-2023-3978
              go get golang.org/x/net@v0.17.0
              go mod tidy
            )
          done

          # Use grpcio >=1.59.0 to be Python 3.12 compat
          sed -i "s/grpcio==.*/grpcio==1.59.0/g" sdk/python/requirements.txt
          sed -i "s/'grpcio==.*'/'grpcio==1.59.0'/g" sdk/python/lib/setup.py
      - runs: |
          set -x

          export PULUMI_VERSION="v${{package.version}}"
          export PULUMI_ROOT="$(mktemp -d)"
          export GOBIN="${PULUMI_ROOT}/bin"
          mkdir -p "${{targets.destdir}}/usr/bin"

          # Build the Pulumi CLI itself
          make install
          mv -v "${PULUMI_ROOT}"/bin/pulumi* "${{targets.destdir}}/usr/bin"

          # Build the Pulumi Language SDKs (Go, Node.js, Python)
          for lang in go nodejs python; do
            cd "sdk/${lang}"

            # go mod tidy is needed because of some go generate stuff that mutates the go.mod
            cd pulumi-language-${lang} && go mod tidy && cd ..
            cd cmd/pulumi-language-${lang} && go mod tidy && cd ../..

            make build

            # "make install_package" is needed for all SDKs except Go
            [[ "${lang}" == "go" ]] || make install_package


            # Remove .cmd files only used on Windows
            rm -f "${PULUMI_ROOT}"/bin/*.cmd
            ls -la "${PULUMI_ROOT}/bin"
            mv -v "${PULUMI_ROOT}"/bin/pulumi* "${{targets.destdir}}/usr/bin"
            cd ../..
          done
      - uses: strip

subpackages:
  - name: "pulumi-language-go"
    description: "Pulumi Language SDK for Go"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/usr/bin"
          mv -v "${{targets.destdir}}"/usr/bin/pulumi-*go* "${{targets.subpkgdir}}/usr/bin"

  - name: "pulumi-language-nodejs"
    description: "Pulumi Language SDK for Node.js"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/usr/bin"
          mv -v "${{targets.destdir}}"/usr/bin/pulumi-*nodejs* "${{targets.subpkgdir}}/usr/bin"
          # pulumi-analyzer-policy is built by the nodejs sdk even though it doesnt contain the string "nodejs"
          mv -v "${{targets.destdir}}"/usr/bin/pulumi-analyzer-policy "${{targets.subpkgdir}}/usr/bin"

  - name: "pulumi-language-python"
    description: "Pulumi Language SDK for Python"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/usr/bin"
          mv -v "${{targets.destdir}}"/usr/bin/pulumi-*python* "${{targets.subpkgdir}}/usr/bin"

update:
  enabled: true
  github:
    identifier: pulumi/pulumi
    strip-prefix: v
