package:
  name: pulumi-kubernetes-operator
  version: 1.13.0
  epoch: 4
  description: A Kubernetes Operator that automates the deployment of Pulumi Stacks
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - go
      - busybox
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pulumi/pulumi-kubernetes-operator.git
      tag: v${{package.version}}
      destination: ${{package.name}}
      expected-commit: 7992cc99d8aed6056e1f68018fadbf21b92c6c6f

  - working-directory: ${{package.name}}
    pipeline:
      - runs: |
          # Mitigate CVE-2023-39325 and CVE-2023-3978
          go get golang.org/x/net@v0.17.0
          go mod tidy

          # Original Go build args found in ./scripts/build.sh
          CGO_ENABLED=0 go build -o "${{targets.destdir}}/usr/bin/${{package.name}}" \
            -ldflags "-s -w -X github.com/pulumi/pulumi-kubernetes-operator/version.Version=v${{package.version}} -extldflags \"-static\"" \
            -tags netgo ./cmd/manager/main.go
      - uses: strip

update:
  enabled: true
  github:
    identifier: pulumi/pulumi-kubernetes-operator
    strip-prefix: v
    tag-filter: v1.1
