package:
  name: pulumi-language-dotnet
  version: 3.57.0
  epoch: 3
  description: Pulumi Language SDK for Dotnet
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - go
      - busybox
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pulumi/pulumi-dotnet.git
      tag: v${{package.version}}
      expected-commit: 16e97ffc0326b91c44ca90869b13f096ea5ec2db

  - uses: go/build
    with:
      packages: .
      output: pulumi-language-dotnet
      ldflags: -s -w -X github.com/pulumi/pulumi-language-dotnet/pkg/version.Version=v${{package.version}}
      modroot: pulumi-language-dotnet
      # Fix CVE-2023-32731 / GHSA-cfgp-2977-2fmm
      # Mitigate CVE-2023-39325 and CVE-2023-3978
      deps: google.golang.org/grpc@v1.53.0 golang.org/x/net@v0.17.0

  - uses: strip

update:
  enabled: true
  github:
    identifier: pulumi/pulumi-dotnet
    strip-prefix: v
