package:
  name: py3-tz
  version: 2023.3
  epoch: 2
  description: Python3 definitions of world timezone
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      uri: https://pypi.python.org/packages/source/p/pytz/pytz-${{package.version}}.tar.gz
      expected-sha512: 3a39e9ec22bf1468e7415f60f10bf4a4e5b0b12bea2aeec45c5e63a916136c747fa0abd1b0612a99da962e743f28f24ebc43c1d73d96f0e98f7fb0ae6b62e319

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 6537
