package:
  name: py3-pgspecial
  version: 2.1.0
  epoch: 1
  description: Meta-commands handler for Postgres Database.
  copyright:
    - license: LICENSE.txt
  dependencies:
    runtime:
      - py3-click
      - py3-sqlparse
      - py3-psycopg
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dbcli/pgspecial
      tag: v${{package.version}}
      expected-commit: d071787d9ed8da3424e43213e6695476923aebdc

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: dbcli/pgspecial
    strip-prefix: v
    use-tag: true
