package:
  name: py3-yaml
  version: 6.0.1
  epoch: 1
  description: "Python3 bindings for YAML"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - python3-dev
      - py3-setuptools
      - yaml-dev
      - cython

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/yaml/pyyaml/archive/${{package.version}}.tar.gz
      expected-sha256: 57314c984aaa84318eed00cf5a8365afc49f87954969e295efe2ba99f3b21f7a

  # from: https://github.com/yaml/pyyaml/issues/601#issuecomment-1740811121
  - uses: patch
    with:
      patches: pyyaml-cython3.patch

  # without --with-libyaml for now
  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - dec-*
  github:
    identifier: yaml/pyyaml
    use-tag: true
