package:
  name: py3-referencing
  version: 0.30.2
  epoch: 2
  description: "Cross-specification JSON referencing (JSON Schema, OpenAPI, and the one you just made up!)."
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3
      - py3-attrs
      - py3-rpds-py

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - python3
      - py3-gpep517
      - py3-pip
      - py3-setuptools
      - py3-wheel

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/python-jsonschema/referencing
      tag: v${{package.version}}
      expected-commit: d37bef22e48b7b91a10dce14904755a539bf15e1

  - runs: |
      # This is needed to work around the error "ValueError: ZIP does not support timestamps before 1980"
      export SOURCE_DATE_EPOCH=315532800
      python3 -m pip install -U hatchling hatch-vcs
      git submodule update --init
      python3 -m gpep517 build-wheel \
        --wheel-dir dist \
        --output-fd 3 3>&1 >&2
      python3 -m installer \
        -d "${{targets.destdir}}" \
        dist/referencing-${{package.version}}-*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: python-jsonschema/referencing
    tag-filter: v
    strip-prefix: v
