package:
  name: py3-pytzdata
  version: "2020.1"
  epoch: 1
  description: The Olson timezone database for Python.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3
      - py3-installer

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - poetry
      - python3-dev
      - py3-wheel
      - py3-gpep517
      - python3
      - py3-setuptools
      - py3-installer
      - py3-pip

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sdispater/pytzdata
      tag: ${{package.version}}
      expected-commit: 11dda19bc50a2d4e246326450bd2e86389cf67c8

  - name: Python Build
    runs: |
      export SETUPTOOLS_SCM_PRETEND_VERSION=${{package.version}}
      pip install -U poetry
      python3 -m gpep517 build-wheel \
       --wheel-dir dist \
       --output-fd 3 3>&1 >&2

      python3 -m installer -d "${{targets.destdir}}" \
       dist/*.whl

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - pool-*
  github:
    identifier: sdispater/pytzdata
    use-tag: true
