package:
  name: py3-fonttools
  version: 4.43.1
  epoch: 1
  description: Tools to manipulate font files
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/fonttools/fonttools
      expected-commit: f8857f6256f1331f97861071c3df22742b61a48a
      tag: ${{package.version}}

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: fonttools/fonttools
