package:
  name: py3-lru-dict
  version: 1.2.0
  epoch: 1
  description: An Dict like LRU container.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - python3-dev
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/amitdev/lru-dict
      tag: v${{package.version}}
      expected-commit: b5ec33e5bb338dd815d2ec8fc6819626ef667821

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: amitdev/lru-dict
    strip-prefix: v
