package:
  name: py3-pygments
  version: 2.16.1
  epoch: 3
  description: Syntax highlighting package written in Python
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - py3-pip

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pygments/pygments.git
      tag: ${{package.version}}
      expected-commit: 9162c079eac12bbf17b187013ab0c46efb7eb43f

  - runs: pip install . --prefix=/usr --root=${{targets.destdir}}

subpackages:
  - name: py3-pygments-doc
    pipeline:
      - runs: |
          destdir=${{targets.subpkgdir}}/usr/share/doc/py3-pygments

          cd "$builddir"

          install -m 644 -D doc/pygmentize.1 \
            ${{targets.subpkgdir}}/usr/share/man/man1/pygmentize.1

          mkdir -p "$destdir"
          cp AUTHORS CHANGES LICENSE "$destdir"/

          # Note: The documentation in the doc directory needs to be generated
          # by py-sphinx
          cp -R ./doc/docs/* "$destdir"/
      - uses: split/manpages
    description: py3-pygments manpages

update:
  enabled: true
  github:
    identifier: pygments/pygments
