package:
  name: py3-networkx
  version: "3.1"
  epoch: 1
  description: Python package for creating and manipulating graphs and networks
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/networkx/networkx
      expected-commit: 9210d9c5bb9875caae0c7be2214abebfdd9255d2
      tag: networkx-${{package.version}}

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - runs: find "${{targets.destdir}}" -type d -name tests -exec rm -r {} \+

  - uses: strip

update:
  enabled: true
  github:
    identifier: networkx/networkx
    strip-prefix: networkx-
