package:
  name: py3-certifi
  version: 2023.07.22
  epoch: 3
  description: "Python3 package for providing Mozilla's CA Bundle"
  copyright:
    - license: MPL-2.0
  dependencies:
    runtime:
      - python3
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-setuptools

# certifi uses a special versioning scheme where the version is a date like "2023.07.22". During the
# build process, the version is "normalized" (and importantly, changed) to a form like "2023.7.22",
# which creates problems with vulnerability scanners, since vulnerability data for certifi is filed
# using its actual version numbers (the "2023.07.22" form). This transform creates the "normalized"
# version, so that we can use it when needed to update the version string back to its original form in
# the Python package's metadata.
var-transforms:
  - from: ${{package.version}}
    match: ([0-9]{4})\.0*([0-9]{1,2})\.0*([0-9]{1,2})
    replace: $1.$2.$3
    to: normalized-package-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/certifi/python-certifi.git
      tag: ${{package.version}}
      expected-commit: 8fb96ed81f71e7097ed11bc4d9b19afd7ea5c909

  - uses: patch
    with:
      patches: use-alpine-system-certs.patch

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"

      # TODO: Need to update this path when building using python-3.12
      sed -i 's/Version: ${{vars.normalized-package-version}}/Version: ${{package.version}}/' "${{targets.destdir}}"/usr/lib/python3.12/site-packages/certifi-${{vars.normalized-package-version}}-py3.12.egg-info/PKG-INFO

  - uses: strip

update:
  enabled: true
  github:
    identifier: certifi/python-certifi
    strip-prefix: v
    use-tag: true
