package:
  name: py3-pybind11
  version: 2.11.1
  epoch: 5
  description: Seamless operability between C++11 and Python
  copyright:
    - license: BSD
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - python3-dev
      - py3-setuptools
      - py3-gpep517
      - py3-wheel
      - cmake

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pybind/pybind11
      tag: v${{package.version}}
      expected-commit: 8a099e44b3d5f85b20f05828d919d2332a8de841

  - name: Python Build
    runs: python setup.py build

  - uses: cmake/configure
    with:
      opts: |
        -DPYTHON_EXECUTABLE=/usr/bin/python3 \
        -DUSE_PYTHON_INCLUDE_DIR=FALSE

  - uses: cmake/build

  - name: Python Install
    runs: |
      python -m gpep517 build-wheel \
        --wheel-dir .dist \
        --output-fd 3 3>&1 >&2
      python3 -m installer -d "${{targets.destdir}}" .dist/*.whl

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: py3-pybind11-dev
    description: pybind11 development headers
    dependencies:
      runtime:
        - py3-pybind11
    pipeline:
      - uses: split/dev
      - runs: |
          mv "${{targets.destdir}}"/usr/share "${{targets.contextdir}}"/usr/share

update:
  enabled: true
  github:
    identifier: pybind/pybind11
    strip-prefix: v
