package:
  name: py3-charset-normalizer
  version: 3.3.0
  epoch: 2
  description: "offers you an alternative to Universal Charset Encoding Detector, also known as Chardet"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/c/charset-normalizer/charset-normalizer-${{package.version}}.tar.gz
      expected-sha256: 63563193aec44bce707e0c5ca64ff69fa72ed7cf34ce6e11d5127555756fd2f6

  - runs: |
      sed -i '/cov-report/d' setup.cfg
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 55366
