package:
  name: py3-alabaster
  version: 0.7.13
  epoch: 1
  description: A configurable sidebar-enabled Sphinx theme
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bitprophet/alabaster
      expected-commit: e5c058385c60901fc6916afe60a6dd26f0a0d6a8
      tag: ${{package.version}}

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: bitprophet/alabaster
