package:
  name: py3-ordered-set
  version: 4.1.0
  epoch: 1
  description: "mutableset which remembers its order"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - python3
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/o/ordered-set/ordered-set-${{package.version}}.tar.gz
      expected-sha256: 694a8e44c87657c59292ede72891eb91d34131f6531463aab3009191c77364a8

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 7433
