package:
  name: py3-hyperopt
  version: 0.2.7
  epoch: 1
  description: Distributed Asynchronous Hyperparameter Optimization
  copyright:
    - license: BSD
  dependencies:
    runtime:
      - numpy
      - py3-scipy
      - py3-six
      - py3-networkx
      - py3-future
      - py3-tqdm
      - py3-cloudpickle
      - py3-py4j
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hyperopt/hyperopt
      expected-commit: dfdb48d1dd9917fad347316a7818a9dcd160f200
      tag: ${{package.version}}

  - name: Python Build
    uses: python/build

  - name: Python Install
    uses: python/install

  - uses: strip

update:
  enabled: true
  github:
    identifier: hyperopt/hyperopt
    use-tag: true
