package:
  name: py3-setproctitle
  version: 1.3.2
  epoch: 1
  description: A Python module to customize the process title
  copyright:
    - license: BSD
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dvarrazzo/py-setproctitle
      tag: version-${{package.version}}
      expected-commit: 7c3b4f1a95f68d2ec3f046a1bdf95a52d930c274

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - version-*
  github:
    identifier: dvarrazzo/py-setproctitle
    use-tag: true
