package:
  name: py3-jsonschema-specifications
  version: 2023.07.1
  epoch: 2
  description: "Cross-specification JSON referencing (JSON Schema, OpenAPI, and the one you just made up!)."
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3
      - py3-referencing

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - python3
      - py3-gpep517
      - py3-pip
      - py3-setuptools
      - py3-wheel

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/python-jsonschema/jsonschema-specifications
      tag: v${{package.version}}
      expected-commit: c22c205e6bc2f93bebf42eefebafc49f96766bce

  - runs: |
      # This is needed to work around the error "ValueError: ZIP does not support timestamps before 1980"
      export SOURCE_DATE_EPOCH=315532800
      python3 -m pip install -U hatchling hatch-vcs
      python3 -m gpep517 build-wheel \
        --wheel-dir dist \
        --output-fd 3 3>&1 >&2
      python3 -m installer \
        -d "${{targets.destdir}}" \
        dist/jsonschema_specifications-*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: python-jsonschema/jsonschema-specifications
    strip-prefix: v
