package:
  name: py3-pip-tools
  version: 7.3.0
  epoch: 1
  description: "A set of command line tools to help you keep your pip-based packages fresh, even when you've pinned them."
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3
      - py3-pip

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - py3-pip

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jazzband/pip-tools
      tag: ${{package.version}}
      expected-commit: 9160b931f0c0623a19879328d206eb0ba1e73a03

  - runs: |
      pip install . --prefix=/usr --root=${{targets.destdir}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: jazzband/pip-tools
    use-tag: true
