package:
  name: py3-joblib
  version: 1.3.2
  epoch: 1
  description: Lightweight pipelining with Python functions
  copyright:
    - license: BSD 3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/joblib/joblib
      expected-commit: 942a41084dbe79743d3114a475dc9e390b8718f1
      tag: ${{package.version}}

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: joblib/joblib
