package:
  name: py3-more-itertools
  version: 10.1.0
  epoch: 2
  description: "more routines for operating on iterables, beyond itertools"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - py3-pip

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/more-itertools/more-itertools.git
      tag: v${{package.version}}
      expected-commit: 266ebdcf9027b7bb6ab72f8cd4585804c1e1547e

  - runs: pip install . --prefix=/usr --root=${{targets.destdir}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: more-itertools/more-itertools
    strip-prefix: v
