package:
  name: py3-werkzeug
  version: 3.0.0
  epoch: 1
  description: The comprehensive WSGI web application library.
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py3-markupsafe
      - python-3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python-3
      - py3-setuptools
      - py3-installer
      - py3-build
      - py3-wheel

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pallets/werkzeug/
      tag: ${{package.version}}
      expected-commit: aa5088f6e550ab6dfb6742270c9ea733ed17261c

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  github:
    identifier: pallets/werkzeug
    use-tag: true
