package:
  name: py3-colorlog
  version: 6.7.0
  epoch: 2
  description: Add colours to the output of Python's logging module.
  copyright:
    - license: MIT License
  dependencies:
    runtime:
      - py3-colorama
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/borntyping/python-colorlog
      expected-commit: f2fe11820af8ae2268b4b666c1777077e34a1672
      tag: v${{package.version}}

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: borntyping/python-colorlog
    strip-prefix: v
