package:
  name: py3-typing
  version: 3.10.0.0
  epoch: 2
  description: Type Hints for Python
  copyright:
    - license: PSF
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      expected-sha256: 13b4ad211f54ddbf93e5901a9967b1e07720c1d1b78d596ac6a439641aa1b130
      uri: https://files.pythonhosted.org/packages/b0/1b/835d4431805939d2996f8772aca1d2313a57e8860fec0e48e8e7dfe3a477/typing-${{package.version}}.tar.gz

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  manual: true # fetch URL contains a sha so will need to be manually
  shared: true
  release-monitor:
    identifier: 10922
