package:
  name: py3-protobuf
  version: 4.24.4
  epoch: 2
  copyright:
    - license: 3-Clause BSD License
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - python3-dev
      - py3-setuptools
      - py3-wheel
      - protobuf-dev

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/p/protobuf/protobuf-${{package.version}}.tar.gz
      expected-sha256: 5a70731910cd9104762161719c3d883c960151eea077134458503723b60e3667

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 46522
