package:
  name: py3-pyjwt
  version: 2.8.0
  epoch: 1
  description: JSON Web Token implementation in Python
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py3-typing-extensions
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools
      - py3-typing-extensions

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jpadilla/pyjwt/
      tag: ${{package.version}}
      expected-commit: 72ad55f6d7041ae698dc0790a690804118be50fc

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: jpadilla/pyjwt
