package:
  name: py3-keras-preprocessing
  version: 1.1.2
  epoch: 1
  description: Easy data preprocessing and data augmentation for deep learning models
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - numpy
      - py3-six
      - python-3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python-3
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      expected-sha256: add82567c50c8bc648c14195bf544a5ce7c1f76761536956c3d2978970179ef3
      uri: https://files.pythonhosted.org/packages/5e/f1/b44337faca48874333769a29398fe4666686733c8880aa160b9fd5dfe600/Keras_Preprocessing-${{package.version}}.tar.gz

  - name: Python Build
    uses: python/build

  - name: Python Install
    uses: python/install

  - uses: strip

update:
  # The modular keras-preprocessing package has been retired upstream in favor of monolithic
  # "keras" package, but Tensorflow itself has not made the jump yet.
  enabled: false
