package:
  name: py3-pathspec
  version: 0.11.2
  epoch: 2
  description: "Utility library for gitignore style pattern matching of file paths"
  copyright:
    - license: MPL-2.0
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/p/pathspec/pathspec-${{package.version}}.tar.gz
      expected-sha512: bb1a178db145fee8011f579fb3a87564245e94b22adfac42bda921d8e2b95cab32617379e22d8ec2bd6aa7e6f9d96c10df4503e638aabfe6b358050912ab98a8

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}" --skip-build

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 23424
