package:
  name: py3-pulsar-client
  version: 3.3.0
  epoch: 1
  description: Apache Pulsar Python client library
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools
      - py3-build
      - py3-installer
      - py3-wheel
      - cmake
      - python3-dev
      - libpulsar-dev
      - py3-pybind11-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/apache/pulsar-client-python
      tag: v${{package.version}}
      expected-commit: f445ceb6c987b571ce10b08357d36f685fdf5802

  - runs: |
      pythonver=$(python3 -c 'import sys; print(str(sys.version_info[0])+"."+str(sys.version_info[1]))')
      cmake -B build -DPYBIND11_INCLUDE_DIRS=/usr/lib/python$pythonver/site-packages/pybind11/include
      cmake --build build
      cmake --install build
      python3 ./setup.py bdist_wheel
      python3 -m installer -d "${{targets.destdir}}" dist/pulsar_client-*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: apache/pulsar-client-python
    strip-prefix: v
    strip-suffix: -candidate1
