package:
  name: py3-kubernetes
  version: 28.1.0
  epoch: 1
  description: Kubernetes python client
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py3-certifi
      - py3-six
      - py3-dateutil
      - py3-yaml
      - py3-google-auth
      - py3-websocket-client
      - py3-requests
      - py3-requests-oauthlib
      - py3-oauthlib
      - py3-urllib3
      - py3-ipaddress
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-client/python
      tag: v${{package.version}}
      expected-commit: 4df2bf398ea69da785a267e58ebe8c289cafd33c

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-client/python
    strip-prefix: v
