package:
  name: py3-py4j
  version: 0.10.9.7
  epoch: 1
  description: Enables Python programs to dynamically access arbitrary Java objects
  copyright:
    - license: BSD License
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools
      - gradle
      - bash
      - openjdk-11
      - py3-sphinx
      - py3-docutils
      - py3-pygments
      - py3-babel
      - py3-packaging
      - py3-jinja2
      - py3-snowballstemmer
      - py3-imagesize
      - py3-requests
      - py3-alabaster
      - py3-sphinxcontrib-applehelp
      - py3-sphinxcontrib-devhelp
      - py3-sphinxcontrib-htmlhelp
      - py3-sphinxcontrib-jsmath
      - py3-sphinxcontrib-qthelp
      - py3-sphinxcontrib-serializinghtml
      - py3-wheel

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/py4j/py4j
      expected-commit: cd479ba858d11272f4852669a6ad33307a7681c4
      tag: ${{package.version}}

  - uses: patch
    with:
      # To fix this error `Reason: UndefinedError("'style' is undefined")`
      patches: disable-copyWebJavadocPython.patch

  - runs: |
      export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
      cd py4j-java
      ./gradlew buildPython

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: py4j/py4j
    use-tag: true
