package:
  name: py3-magic
  version: 0.4.27
  epoch: 3
  description: "Python3 wrapper for libmagic"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3
      - libmagic

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/ahupp/python-magic/archive/${{package.version}}.tar.gz
      expected-sha512: a476730a5caa9a2a784187f57743d5cec4b1829a6a76d4d1fb4e0112caf5487888961df293bc38074ef1a5d313b0fc4aed4cc99b980f5336e8a907c44a33e84e

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --skip-build --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: ahupp/python-magic
    use-tag: true
