package:
  name: py3-pkgconfig
  version: 1.5.5
  epoch: 2
  description: Interface Python with pkg-config
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python-3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python-3
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      expected-sha256: deb4163ef11f75b520d822d9505c1f462761b4309b1bb713d08689759ea8b899
      uri: https://files.pythonhosted.org/packages/c4/e0/e05fee8b5425db6f83237128742e7e5ef26219b687ab8f0d41ed0422125e/pkgconfig-${{package.version}}.tar.gz

  - name: Python Build
    uses: python/build

  - name: Python Install
    uses: python/install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 209128
