package:
  name: py3-webencodings
  version: 0.5.1
  epoch: 2
  description: Character encoding aliases for legacy web content
  copyright:
    - license: BSD
  dependencies:
    runtime:
      - python-3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python-3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gsnedders/python-webencodings
      tag: v${{package.version}}
      expected-commit: fa2cb5d75ab41e63ace691bc0825d3432ba7d694

  - name: Python Build
    uses: python/build

  - name: Python Install
    uses: python/install

  - uses: strip

update:
  enabled: true
  github:
    identifier: gsnedders/python-webencodings
    strip-prefix: v
