package:
  name: py3-astunparse
  version: 1.6.3
  epoch: 1
  description: An AST unparser for Python
  copyright:
    - license: BSD
  dependencies:
    runtime:
      - py3-wheel
      - py3-six
      - python-3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python-3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/simonpercivall/astunparse
      tag: v${{package.version}}
      expected-commit: 2acce01fcdda2ea32eea835c30ccca21aaff7297

  - name: Python Build
    uses: python/build

  - name: Python Install
    uses: python/install

  - uses: strip

update:
  enabled: true
  github:
    identifier: simonpercivall/astunparse
    strip-prefix: v
