package:
  name: py3-wcmatch
  version: "8.5"
  epoch: 1
  description: "Wilcard File Name matching library."
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3
      - py3-bracex

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - python3
      - py3-gpep517
      - py3-pip
      - py3-setuptools
      - py3-wheel

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/facelessuser/wcmatch
      tag: ${{package.version}}
      expected-commit: ff57d25c4104bc6e7e8d9e962ffec88b293b9bdb

  - runs: |
      # This is needed to work around the error "ValueError: ZIP does not support timestamps before 1980"
      export SOURCE_DATE_EPOCH=315532800
      python3 -m pip install -U hatchling
      python3 -m gpep517 build-wheel \
        --wheel-dir dist \
        --output-fd 3 3>&1 >&2
      python3 -m installer \
        -d "${{targets.destdir}}" \
        dist/wcmatch-${{package.version}}-*.whl
      install -Dm644 LICENSE.md \
        "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/LICENSE

  - uses: strip

update:
  enabled: true
  github:
    identifier: facelessuser/wcmatch
