package:
  name: py3-contourpy
  version: 1.1.1
  epoch: 1
  description: Python library for calculating contours of 2D quadrilateral grids
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - numpy
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - python3-dev
      - py3-setuptools
      - py3-pip
      - py3-installer
      - py3-pybind11-dev
      - py3-build

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/contourpy/contourpy
      expected-commit: 2606b9e2eb93b0f1127dfeca3d868cd78f4c874d
      tag: v${{package.version}}

  - name: Python Build
    runs: |
      python3 -m build

  - runs: |
      python3 -m installer -d "${{targets.destdir}}" dist/*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: contourpy/contourpy
    strip-prefix: v
