package:
  name: py3-ply
  version: 3.11_git20180215
  epoch: 2
  description: Python Lex & Yacc
  copyright:
    - license: BSD
  dependencies:
    runtime:
      - python3

var-transforms:
  - from: ${{package.version}}
    match: _git(.*)
    replace: ''
    to: mangled-package-version

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dabeaz/ply
      tag: ${{vars.mangled-package-version}}
      expected-commit: 0f398b72618c1564d71f7dc0558e6722b241875a

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

# some sort of a deprecated project
update:
  enabled: false
