package:
  name: py3-pendulum
  version: 2.1.2
  epoch: 1
  description: Python datetimes made easy
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py3-dateutil
      - py3-typing
      - py3-pytzdata
      - python3

environment:
  contents:
    repositories:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3-dev
      - poetry
      - py3-wheel
      - py3-gpep517
      - python3
      - py3-setuptools
      - py3-installer
      - py3-pip

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sdispater/pendulum
      tag: ${{package.version}}
      expected-commit: d9aa101fe76852b75cba14d686ede923641c5b4d

  - name: Python Build
    runs: python build.py build

  - runs: |
      export SETUPTOOLS_SCM_PRETEND_VERSION=${{package.version}}
      pip install -U poetry
       python3 -m gpep517 build-wheel \
       --wheel-dir dist \
       --output-fd 3 3>&1 >&2

       python3 -m installer -d "${{targets.destdir}}" \
       dist/*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: sdispater/pendulum
    use-tag: true
  ignore-regex-patterns:
    - '.*a.*' # ignore tags like 3.0.0a1
    - '.*b.*' # ignore tags like 3.0.0b1
