package:
  name: py3-babel
  version: 2.13.0
  epoch: 1
  description: Python3 i18n tool
  copyright:
    - license: "BSD-3-Clause"
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/B/Babel/Babel-${{package.version}}.tar.gz
      expected-sha512: 43f4b5fdd8653639111a767c4b082333d89695507e92c3fca88262f23ee7531d4600ec794e908e78a64da1ec54020c7127df3deaf979e15c4e1067cdb839aa47

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  shared: true
  release-monitor:
    identifier: 11984
