package:
  name: py3-alembic
  version: 1.11.3
  epoch: 3
  description: A database migration tool for SQLAlchemy.
  copyright:
    - license: MIT License
  dependencies:
    runtime:
      - python3
      - py3-mako
      - py3-dateutil
      - py3-sqlalchemy
      - py3-python-editor

# transform melange version 1.11.3 => 1_11_3
var-transforms:
  - from: ${{package.version}}
    match: \.
    replace: _
    to: mangled-package-version

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sqlalchemy/alembic
      expected-commit: 47850ab7dbc88905db8abf7abab6a48699d4a50a
      tag: rel_${{vars.mangled-package-version}}

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: false # This requires manual updates because of the strange tagging scheme.
  manual: true
  github:
    identifier: sqlalchemy/alembic
