package:
  name: py3-cmaes
  version: 0.10.0
  epoch: 2
  description: Lightweight Covariance Matrix Adaptation Evolution Strategy (CMA-ES) implementation for Python 3.
  copyright:
    - license: MIT License
  dependencies:
    runtime:
      - numpy
      - py3-scipy
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/CyberAgentAILab/cmaes
      expected-commit: 4ebcdbd412333893bd2674bc694924e21abf8915
      tag: v${{package.version}}

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: CyberAgentAILab/cmaes
    strip-prefix: v
