package:
  name: py3-absl-py
  version: 2.0.0
  epoch: 1
  description: Abseil Python Common Libraries, see https://github.com/abseil/abseil-py.
  copyright:
    - license: Apache 2.0
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/abseil/abseil-py/
      tag: v${{package.version}}
      expected-commit: 37dad4d356ca9e13f1c533ad6309631b397a2b6b

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: abseil/abseil-py
    strip-prefix: v
