package:
  name: py3-pluggy
  version: 1.3.0
  epoch: 3
  description: "Plugin management and hook calling for Python"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-setuptools
      - py3-pip

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/p/pluggy/pluggy-${{package.version}}.tar.gz
      expected-sha512: d4dbb449f533649da161d7e49f82da5800dabdace4f7aa239c412290470612a45a3ba3c50cafd7bd9ed26cb3aa14648bfa3ed3f41fc0db9ae9399fd7f5933d5f

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 7500
