package:
  name: py3-pgcli
  version: 3.5.0
  epoch: 1
  description: CLI for Postgres Database. With auto-completion and syntax highlighting.
  copyright:
    - license: BSD
  dependencies:
    runtime:
      - py3-pgspecial
      - py3-click
      - py3-pygments
      - py3-prompt-toolkit
      - py3-psycopg
      - py3-sqlparse
      - py3-configobj
      - py3-pendulum
      - py3-cli-helpers
      - py3-setproctitle
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dbcli/pgcli
      tag: v${{package.version}}
      expected-commit: c280f8e398662e43a1637c6918700f0883baea1c

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: dbcli/pgcli
    strip-prefix: v
    use-tag: true
