package:
  name: py3-future
  version: 0.18.3
  epoch: 1
  description: Clean single-source support for Python 3 and 2
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/PythonCharmers/python-future
      expected-commit: af1db970b0879b59e7aeb798c27a623144561cff
      tag: v${{package.version}}

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: PythonCharmers/python-future
    strip-prefix: v
