package:
  name: py3-pyyaml
  version: 6.0.1
  epoch: 2
  description: YAML parser and emitter for Python
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/yaml/pyyaml
      tag: ${{package.version}}
      expected-commit: c42fa3bff1eabdb64763bb1526d9ea1ccb708479

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: yaml/pyyaml
