package:
  name: py3-opt-einsum
  version: 3.3.0
  epoch: 1
  description: Optimizing numpys einsum function
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - numpy
      - python-3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python-3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dgasmith/opt_einsum
      tag: v${{package.version}}
      expected-commit: c826bb7df16f470a69f7bf90598fc27586209d11

  - uses: patch
    with:
      patches: 7c8f193f90b6771a6b3065bb5cf6ec2747af8209.patch

  - name: Python Build
    uses: python/build

  - name: Python Install
    uses: python/install

  - uses: strip

update:
  enabled: true
  github:
    identifier: dgasmith/opt_einsum
    strip-prefix: v
