package:
  name: py3-tensorflow-metadata
  version: 1.14.0
  epoch: 1
  description: Utilities for passing TensorFlow-related metadata between tools
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py3-absl-py
      - py3-googleapis-common-protos
      - py3-protobuf
      - python-3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python-3
      - py3-setuptools
      - bazel-6
      - openjdk-17
      - bash
  environment:
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 7073f7452d6cecbb5279781451f7c3144c924367
      repository: https://github.com/tensorflow/metadata
      tag: v${{package.version}}

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  manual: false
  github:
    identifier: tensorflow/metadata
    strip-prefix: v
