package:
  name: py3-pythran
  version: 0.14.0
  epoch: 2
  description: Ahead of Time compiler for numeric kernels
  copyright:
    - license: BSD 3-Clause
  dependencies:
    runtime:
      - py3-ply
      - py3-gast
      - numpy
      - py3-beniget
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/serge-sans-paille/pythran
      tag: ${{package.version}}
      expected-commit: b4a3abc0da4d40f55cdc671f5339c6f975362f96

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  ignore-regex-patterns:
    - .post1
  enabled: true
  github:
    identifier: serge-sans-paille/pythran
    use-tag: true
