package:
  name: py3-sqlalchemy
  version: 2.0.20
  epoch: 2
  description: Database Abstraction Library
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

# transform melange version 2.0.20 => 2_0_20
var-transforms:
  - from: ${{package.version}}
    match: \.
    replace: _
    to: mangled-package-version

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sqlalchemy/sqlalchemy
      expected-commit: a52103c44f3989d53edf4c76abb92afd3ca724c9
      tag: rel_${{vars.mangled-package-version}}

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: false # This requires manual updates because of the strange tagging scheme.
  manual: true
  github:
    identifier: sqlalchemy/sqlalchemy
