package:
  name: py3-markdown
  version: "3.5"
  epoch: 1
  description: Python implementation of John Gruber's Markdown.
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py3-importlib-metadata
      - python-3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python-3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Python-Markdown/markdown
      tag: ${{package.version}}
      expected-commit: 4f0b91abe1a954a72ab3c99c3e2b880ab36631fa

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - ^\d+\.\d+\.final$
    - ^\d+\.\d+.\d+\.final$
  github:
    identifier: Python-Markdown/markdown
    use-tag: true
