package:
  name: py3-libarchive-c
  version: 5.0
  epoch: 1
  description: "Python interface to libarchive."
  copyright:
    - license: CC0-1.0

environment:
  contents:
    packages:
      - busybox
      - build-base
      - wolfi-baselayout
      - python3
      - py3-setuptools
      - libarchive
      - libarchive-dev
      - scanelf

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/l/libarchive-c/libarchive-c-${{package.version}}.tar.gz
      expected-sha256: d673f56673d87ec740d1a328fa205cafad1d60f5daca4685594deb039d32b159

  # Use the correct library soname
  # NOTE: find_library is broken on aarch64, so just hardcode it for now.
  - runs: |
      soname=$(scanelf --quiet --soname /usr/lib/libarchive.so | awk '{print $1}')
      sed -i -e "s:find_library('archive'):'/usr/lib/$soname':" libarchive/ffi.py

  - runs: |
      python3 setup.py build
      python3 setup.py install --skip-build --root="${{targets.destdir}}"

update:
  enabled: true
  release-monitor:
    identifier: 9954
