package:
  name: py3-beniget
  version: 0.4.1
  epoch: 2
  description: Extract semantic information about static Python code
  copyright:
    - license: BSD 3-Clause
  dependencies:
    runtime:
      - py3-gast
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/serge-sans-paille/beniget
      tag: ${{package.version}}
      expected-commit: 4e4d587e0e023eafb9fb935c210aad35ac04e0d3

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: serge-sans-paille/beniget
    use-tag: true
