package:
  name: py3-tqdm
  version: 4.66.1
  epoch: 1
  description: Fast, Extensible Progress Meter
  copyright:
    - license: MPL-2.0 AND MIT
  dependencies:
    runtime:
      - py3-colorama
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python3
      - py3-setuptools
      - py3-pip

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tqdm/tqdm
      tag: v${{package.version}}
      expected-commit: 4c956c20b83be4312460fc0c4812eeb3fef5e7df

  - runs: python3 -m pip install --upgrade build

  - runs: python3 -m pip install --upgrade twine

  - runs: python3 -m build

  - runs: python3 -m twine check dist/*

update:
  enabled: true
  github:
    identifier: tqdm/tqdm
    strip-prefix: v
