package:
  name: py3-keras-applications
  version: 1.0.8
  epoch: 1
  description: Reference implementations of popular deep learning models
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - numpy
      - py3-h5py
      - python-3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python-3
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      expected-sha256: 5579f9a12bcde9748f4a12233925a59b93b73ae6947409ff34aa2ba258189fe5
      uri: https://files.pythonhosted.org/packages/21/56/4bcec5a8d9503a87e58e814c4e32ac2b32c37c685672c30bc8c54c6e478a/Keras_Applications-${{package.version}}.tar.gz

  - name: Python Build
    uses: python/build

  - name: Python Install
    uses: python/install

  - uses: strip

update:
  # The modular keras-preprocessing package has been retired upstream in favor of monolithic
  # "keras" package, but Tensorflow itself has not made the jump yet.
  enabled: false
