package:
  name: py3-html5lib
  version: "1.1"
  epoch: 1
  description: HTML parser based on the WHATWG HTML specification
  copyright:
    - license: MIT License
  dependencies:
    runtime:
      - py3-six
      - py3-webencodings
      - python-3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python-3
      - py3-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/html5lib/html5lib-python
      tag: ${{package.version}}
      expected-commit: f87487a4ada2d6cf223bdd182774a01ba3c84618

  - name: Python Build
    uses: python/build

  - name: Python Install
    uses: python/install

  - uses: strip

update:
  enabled: true
  github:
    identifier: html5lib/html5lib-python
    use-tag: true
