package:
  name: py3.12-installer
  version: 0.7.0
  epoch: 4
  description: A library for installing Python wheels.
  copyright:
    - license: "MIT"
  dependencies:
    provides:
      - py3-installer=${{package.full-version}}
    runtime:
      - python-3.12

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - py3.12-pip

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pypa/installer.git
      tag: ${{package.version}}
      expected-commit: b1d39180f8548820d09ce992dfadff0a42242c48

  - name: Python Install
    runs: pip install . --prefix=/usr --root=${{targets.destdir}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: pypa/installer
    use-tag: true
