package:
  name: redis-7.2
  version: 7.2.2
  epoch: 0
  description: Advanced key-value store
  copyright:
    - license: BSD-3-Clause
  dependencies:
    provides:
      - redis=${{package.full-version}}
    runtime:
      - posix-libc-utils # `getent` is required on startup in ha mode for ip introspection cluster formation

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - linux-headers
      - openssl-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: ca999be08800edc6d265379c4c7aafad92f0ee400692e4e2d69829ab4b4c3d08
      uri: https://download.redis.io/releases/redis-${{package.version}}.tar.gz

  - uses: patch
    with:
      patches: 0000-Disable-protected-mode.patch

  - runs: |
      export CFLAGS="$CFLAGS -DUSE_MALLOC_USABLE_SIZE"
        make USE_JEMALLOC=no \
        MALLOC=libc \
        BUILD_TLS=yes \
        all -j$(nproc)
      make install PREFIX=/usr INSTALL_BIN="${{targets.destdir}}/usr/bin"

  - uses: strip

subpackages:
  - name: redis-cli-7.2
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/redis-cli "${{targets.subpkgdir}}"/usr/bin/redis-cli
    description: redis-cli is the command line interface utility to talk with Redis.
    dependencies:
      provides:
        - redis-cli=${{package.full-version}}

  - name: redis-benchmark-7.2
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/redis-benchmark "${{targets.subpkgdir}}"/usr/bin/redis-benchmark
    description: redis-benchmark utility that simulates running commands done by N clients while at the same time sending M total queries.
    dependencies:
      provides:
        - redis-benchmark=${{package.full-version}}

  - name: redis-7.2-bitnami-compat
    dependencies:
      provides:
        - redis-bitnami-compat=${{package.full-version}}
      runtime:
        - libxcrypt
        - redis
        # Required by startup scripts
        - busybox
        - bash
        - openssl
        - redis-cli
    pipeline:
      - uses: bitnami/compat
        with:
          image: redis
          version-path: 7.2/debian-11
      - runs: |
          ln -s /opt/bitnami/scripts/redis/entrypoint.sh ${{targets.subpkgdir}}/entrypoint.sh
          ln -s /opt/bitnami/scripts/redis/run.sh ${{targets.subpkgdir}}/run.sh

  # redis-sentinel is a symlink to redis-server, but paired with differently named startup scripts in bitnami
  - name: redis-sentinel-7.2-bitnami-compat
    dependencies:
      provides:
        - redis-sentinel-bitnami-compat=${{package.full-version}}
      runtime:
        - redis
        - libxcrypt
        # Required by startup scripts
        - busybox
        - bash
        - openssl
        - redis-cli
    pipeline:
      - uses: bitnami/compat
        with:
          image: redis-sentinel
          version-path: 7.2/debian-11

  # in bitnami, redis-cluster is redis-server paired with different startup to support cluster mode
  # keep this as a subpackage in redis to avoid confusion
  - name: redis-cluster-7.2-bitnami-compat
    dependencies:
      provides:
        - redis-cluster-bitnami-compat=${{package.full-version}}
      runtime:
        - libxcrypt
        - redis
        # Required by startup scripts
        - busybox
        - bash
        - openssl
        - redis-cli
    pipeline:
      - uses: bitnami/compat
        with:
          image: redis-cluster
          version-path: 7.2/debian-11

update:
  enabled: true
  github:
    identifier: redis/redis
