package:
  name: redis-6.2
  version: 6.2.14
  epoch: 0
  description: Advanced key-value store
  copyright:
    - license: BSD-3-Clause
  dependencies:
    provides:
      - redis=6.2.99
      # Kept for compatibility with `redis-sentinel-6.2-compat`
      - redis-sentinel-6.2
    runtime:
      - posix-libc-utils # `getent` is required on startup in ha mode for ip introspection cluster formation

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - linux-headers
      - openssl-dev

pipeline:
  - uses: fetch
    with:
      uri: https://download.redis.io/releases/redis-${{package.version}}.tar.gz
      expected-sha512: 140d4b23c20d459b65be8c61996e281222f978b51c52cb048039d741801e4027775ad89ed354dc0dce3d47703a08610adafaf6253fea2f973d5b9d20bc1e59ce

  - uses: patch
    with:
      patches: 0000-Disable-protected-mode.patch

  - runs: |
      export CFLAGS="$CFLAGS -DUSE_MALLOC_USABLE_SIZE"
        make USE_JEMALLOC=no \
        MALLOC=libc \
        BUILD_TLS=yes \
        all -j$(nproc)
      make install PREFIX=/usr INSTALL_BIN="${{targets.destdir}}/usr/bin"

  - uses: strip

subpackages:
  - name: redis-cli-6.2
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/redis-cli "${{targets.subpkgdir}}"/usr/bin/redis-cli
    description: redis-cli is the command line interface utility to talk with Redis.
    dependencies:
      provides:
        - redis-cli=6.2.99

  - name: redis-benchmark-6.2
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/redis-benchmark "${{targets.subpkgdir}}"/usr/bin/redis-benchmark
    description: redis-benchmark utility that simulates running commands done by N clients while at the same time sending M total queries.
    dependencies:
      provides:
        - redis-benchmark=6.2.99

  - name: ${{package.name}}-bitnami-compat
    dependencies:
      runtime:
        - libxcrypt
        - redis-6.2
        # Required by startup scripts
        - busybox
        - bash
        - openssl
        - redis-cli-6.2
      provides:
        - redis-bitnami-compat=6.2.99
    pipeline:
      - uses: bitnami/compat
        with:
          image: redis
          version-path: 6.2/debian-11
      - runs: |
          ln -s /opt/bitnami/scripts/redis/entrypoint.sh ${{targets.subpkgdir}}/entrypoint.sh
          ln -s /opt/bitnami/scripts/redis/run.sh ${{targets.subpkgdir}}/run.sh

  # redis-sentinel is a symlink to redis-server, but paired with differently named startup scripts in bitnami
  # keep this as a subpackage in redis to avoid confusion
  - name: redis-sentinel-6.2-bitnami-compat
    dependencies:
      runtime:
        - libxcrypt
        - redis-6.2
        # Required by startup scripts
        - busybox
        - bash
        - openssl
        - redis-cli-6.2
      provides:
        - redis-sentinel-bitnami-compat=6.2.99
    pipeline:
      - uses: bitnami/compat
        with:
          image: redis-sentinel
          version-path: 6.2/debian-11

  # in bitnami, redis-cluster is redis-server paired with different startup to support cluster mode
  # keep this as a subpackage in redis to avoid confusion
  - name: redis-cluster-6.2-bitnami-compat
    dependencies:
      runtime:
        - libxcrypt
        - redis-6.2
        # Required by startup scripts
        - busybox
        - bash
        - openssl
        - redis-cli-6.2
      provides:
        - redis-cluster-bitnami-compat=6.2.99
    pipeline:
      - uses: bitnami/compat
        with:
          image: redis-cluster
          version-path: 6.2/debian-11

update:
  enabled: true
  github:
    identifier: redis/redis
    tag-filter: "6.2"
