package:
  name: reflex
  version: 0.2.9
  epoch: 1
  description: "Web apps in pure Python"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - python3
      # Reflex shells out to these these tools during init
      - bash
      - wget
      - curl

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - poetry
      - py3-pip
      - py3-setuptools
      - python3
      - python3-dev
      - wolfi-base
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/reflex-dev/reflex
      tag: v${{package.version}}
      expected-commit: 86c624e93976567c6b4393fe1b06ca22c4fd3472

  - runs: |
      poetry build
      pip install --root ${{targets.destdir}} dist/reflex-*.whl
      find ${{targets.destdir}}/usr/lib/python*/site-packages/ \( -type d -a -name test -o -name tests \) -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) -exec rm -rf '{}' \+

  - uses: strip

update:
  enabled: true
  github:
    identifier: reflex-dev/reflex
    strip-prefix: v
