package:
  name: rekor
  version: 1.3.2
  epoch: 1
  description: Software Supply Chain Transparency Log
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
      paths:
        - "*"
  checks:
    disabled:
      - empty

environment:
  contents:
    packages:
      - busybox
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sigstore/rekor
      tag: v${{package.version}}
      expected-commit: 1c2ae1c9d74af411ebecd1d947972bfc7d8c8938

subpackages:
  - name: ${{package.name}}-server
    pipeline:
      - uses: go/build
        with:
          modroot: .
          subpackage: "true"
          packages: ./cmd/rekor-server
          output: rekor-server
          ldflags: -w
      - uses: strip

  - name: ${{package.name}}-cli
    pipeline:
      - uses: go/build
        with:
          modroot: .
          subpackage: "true"
          packages: ./cmd/rekor-cli
          output: rekor-cli
          ldflags: -w
      - uses: strip

  - name: ${{package.name}}-backfill-redis
    pipeline:
      - uses: go/build
        with:
          modroot: .
          subpackage: "true"
          packages: ./cmd/backfill-redis
          output: backfill-redis
          ldflags: -w
      - uses: strip

update:
  enabled: true
  github:
    identifier: sigstore/rekor
    strip-prefix: v
