package:
  name: s3cmd
  version: 2.3.0
  epoch: 1
  description: Command-line tool for managing Amazon S3 and CloudFront services
  copyright:
    - license: GPL-2.0-or-later
  dependencies:
    runtime:
      - python3
      - py3-dateutil
      - py3-magic

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/s3tools/s3cmd/archive/v${{package.version}}/s3cmd-${{package.version}}.tar.gz
      expected-sha512: ca3e565b55a02a4a3655f0982906f72aa030eabc97424d350f533efc7d3a231ae971efab5b6180635f6a26a11b1a32e278f806c6ddf10d433787826a2949ea71

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --root="${{targets.destdir}}" --skip-build

  - uses: strip

update:
  enabled: true
  github:
    identifier: s3tools/s3cmd
    strip-prefix: v
