package:
  name: secrets-store-csi-driver
  # When bumping the version check if the CVE mitigations below can be removed.
  version: 1.3.4
  epoch: 6
  description: Secrets Store CSI driver for Kubernetes secrets
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - busybox # the csi driver needs the 'mount' applet

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - build-base
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/secrets-store-csi-driver
      tag: v${{package.version}}
      expected-commit: 4f12da0d5c4ac8487373c05394a4568a7d5d5e56

  - runs: |
      # fix CVE-2023-39325 ,CVE-2023-3978 and CVE-2023-44487
      go get golang.org/x/net@v0.17.0
      go mod tidy

      # Our global LDFLAGS conflict with a Makefile parameter: https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/Makefile#LL49C3-L49C3
      unset LDFLAGS
      make build

  - runs: |
      install -Dm755 _output/secrets-store-csi ${{targets.destdir}}/usr/bin/secrets-store-csi

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/secrets-store-csi-driver
    strip-prefix: v
