package:
  name: secrets-store-csi-driver-provider-gcp
  # When bumping the version check if the GHSA mitigations below can be removed.
  version: 1.3.0
  epoch: 6
  description: Google Secret Manager provider for the Secret Store CSI Driver.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - wolfi-baselayout
      - busybox
      - build-base
      - go
      - ca-certificates-bundle

pipeline:
  # We can't use go/install because this requires specific ldflags to set the version
  - uses: git-checkout
    with:
      repository: https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp
      tag: v${{package.version}}
      expected-commit: 7eb0775d3e47d4c81e9c2a4b324cab9e80826fa0

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin/

      # fix CVE-2023-39325 ,CVE-2023-3978 and CVE-2023-44487
      go get golang.org/x/net@v0.17.0
      go mod tidy

      go build \
        -ldflags "-w -extldflags '-static' -X 'main.version=${{package.version}}'" \
        -o ${{targets.destdir}}/usr/bin/secrets-store-csi-driver-provider-gcp .

  - uses: strip

update:
  enabled: true
  github:
    identifier: GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp
    strip-prefix: v
