package:
  name: sigstore-scaffolding
  version: 0.6.8
  epoch: 4
  description: Software Supply Chain Transparency Log
  copyright:
    - license: Apache-2.0
  checks:
    disabled:
      - empty

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - git
      - go

data:
  - name: components
    items:
      ctlog-createctconfig: ./cmd/ctlog/createctconfig
      ctlog-managectroots: ./cmd/ctlog/managectroots
      ctlog-verifyfulcio: ./cmd/ctlog/verifyfulcio
      fulcio-createcerts: ./cmd/fulcio/createcerts
      getoidctoken: ./cmd/getoidctoken
      rekor-createsecret: ./cmd/rekor/createsecret
      trillian-createdb: ./cmd/trillian/createdb
      trillian-createtree: ./cmd/trillian/createtree
      trillian-updatetree: ./cmd/trillian/updatetree
      tsa-createcertchain: ./cmd/tsa/createcertchain
      tuf-createsecret: ./cmd/tuf/createsecret
      tuf-server: ./cmd/tuf/server

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sigstore/scaffolding
      tag: v${{package.version}}
      expected-commit: 76f6bf19030792b4fa88fcffd188975ffe84514e

subpackages:
  - range: components
    name: "${{package.name}}-${{range.key}}"
    pipeline:
      - uses: go/build
        with:
          modroot: .
          subpackage: "true"
          packages: ${{range.value}}
          output: ${{range.key}}
          ldflags: -w
          # CVE-2023-39325 and CVE-2023-3978
          deps: golang.org/x/net@v0.17.0
      - uses: strip

  - name: "${{package.name}}-cloudsqlproxy"
    pipeline:
      - uses: go/build
        with:
          modroot: .
          subpackage: "true"
          packages: ./cmd/cloudsqlproxy
          output: cloudsqlproxy
          ldflags: -w
      - uses: strip
    dependencies:
      runtime:
        - cloud-sql-proxy
        - cloud-sql-proxy-compat

update:
  enabled: true
  github:
    identifier: sigstore/scaffolding
    strip-prefix: v
