package:
  name: spark-operator
  version: 1.1.27
  epoch: 13
  description: Kubernetes operator for managing the lifecycle of Apache Spark applications on Kubernetes.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - git
      - go
      - tini

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator
      tag: spark-operator-chart-${{package.version}}
      expected-commit: bd2eda216b79733c992861f257b28dad36bb4c62

  - runs: |
      # GHSA-ppp9-7jff-5vj2
      # GHSA-69ch-w2m2-3vjp
      go get -u golang.org/x/text@v0.3.8

      # GHSA-h86h-8ppg-mxmh
      # GHSA-83g2-8m93-v3w7
      # GHSA-69cg-p879-7622
      # GHSA-vvpx-j8f3-3w6h
      go get -u golang.org/x/net@v0.17.0

      # Remediate GHSA-qc2g-gmh6-95p4
      go mod edit -replace k8s.io/kubernetes=k8s.io/kubernetes@v1.19.15

      go mod tidy
      mkdir -p ${{targets.destdir}}/usr/bin
      go build -trimpath -ldflags "-w" -o ${{targets.destdir}}/usr/bin/spark-operator .

  - uses: strip

subpackages:
  - name: "sparkctl"
    pipeline:
      - runs: |
          cd sparkctl
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          go build -trimpath -ldflags "-w" -buildvcs=false -o ${{targets.subpkgdir}}/usr/bin/sparkctl .
      - uses: strip

  - name: spark-operator-oci-entrypoint
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          cp hack/gencerts.sh  ${{targets.subpkgdir}}/usr/bin/
          chmod 0755 ${{targets.subpkgdir}}/usr/bin/gencerts.sh
          cp entrypoint.sh ${{targets.subpkgdir}}/usr/bin/
          chmod 0755 ${{targets.subpkgdir}}/usr/bin/entrypoint.sh
          # entrypoints expects tini to be on /sbin/tini
          # https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/entrypoint.sh#LL27C5-L27C19
          ln -s /sbin/tini ${{targets.subpkgdir}}/usr/bin/tini
    dependencies:
      runtime:
        - openssl
        - tini
        - posix-libc-utils
        - coreutils

update:
  enabled: true
  github:
    identifier: GoogleCloudPlatform/spark-on-k8s-operator
    strip-prefix: spark-operator-chart-
    use-tag: true
    tag-filter: "spark-operator-chart-"
