package:
  name: suricata-update
  version: 1.2.7
  epoch: 2
  description: "The tool for updating your Suricata rules"
  copyright:
    - license: GPL-2.0-only
  dependencies:
    runtime:
      - python3
      - py3-yaml

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - py3-pip

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/OISF/suricata-update/archive/refs/tags/${{package.version}}.tar.gz
      expected-sha256: 0b024b564f1fc5e20db3bf824ae8aabc47fff630cf2632a5e820c18000ebbf5e

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 17309
