package:
  name: tctl
  version: 1.18.0
  epoch: 0
  description: Temporal CLI
  copyright:
    - license: MIT License

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/temporalio/tctl
      tag: v${{package.version}}
      expected-commit: aed2d9e1cb8bba6f69d5463fa286eb0389149ee4
      destination: tctl

  - runs: |
      cd tctl
      make build
      install -Dm755 tctl ${{targets.destdir}}/usr/bin/tctl
      install -Dm755 tctl-authorization-plugin ${{targets.destdir}}/usr/bin/tctl-authorization-plugin

  - uses: strip

update:
  enabled: true
  github:
    identifier: temporalio/tctl
    strip-prefix: v
