package:
  name: tekton-chains
  version: 0.18.0
  epoch: 3
  description: Supply Chain Security in Tekton Pipelines
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tektoncd/chains
      tag: v${{package.version}}
      expected-commit: 52b918e6332410f68922fe8e561013c31e4c81cc
      destination: chains

  - runs: |
      cd chains
      go get golang.org/x/net@v0.17.0
      go mod tidy

  - uses: go/build
    with:
      packages: ./cmd/controller
      output: tekton-chains
      modroot: chains
      vendor: true
      deps: github.com/cloudflare/circl@v1.3.3 github.com/docker/distribution@v2.8.2

update:
  enabled: true
  github:
    identifier: tektoncd/chains
    strip-prefix: v
