package:
  name: terragrunt
  version: 0.52.3
  epoch: 0
  description: Thin wrapper for Terraform providing extra tools
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - terraform

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - build-base
      - go

pipeline:
  - uses: fetch
    with:
      expected-sha256: 4fb787fdd7f1572f65ca584c8f6f6d79f0cf2a28377f1e081e891fed0ac010a8
      uri: https://github.com/gruntwork-io/terragrunt/archive/refs/tags/v${{package.version}}.tar.gz

  - runs: |
      go build -v -o bin/terragrunt -ldflags "-s -w -X main.VERSION=v${{package.version}}"
      install -Dm755 bin/terragrunt "${{targets.destdir}}"/usr/bin/terragrunt

  - uses: strip

update:
  enabled: true
  github:
    identifier: gruntwork-io/terragrunt
    strip-prefix: v
    use-tag: true
    tag-filter: v
