package:
  name: thanos-0.32
  version: 0.32.4
  epoch: 3
  description: Highly available Prometheus setup with long term storage capabilities.
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - thanos=0.32.999

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - bash
      - go
      - curl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/thanos-io/thanos
      tag: v${{package.version}}
      expected-commit: fcd5683e3049924ae26a680e166ae6f27a344896

  - runs: |
      # Mitigate CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy

      make build

  - runs: |
      install -Dm755 .cache/go/bin/thanos "${{targets.destdir}}"/usr/bin/thanos

  - uses: strip

update:
  enabled: true
  github:
    identifier: thanos-io/thanos
    strip-prefix: v
    tag-filter: v0.32.
