package:
  name: thanos-0.31
  version: 0.31.0
  epoch: 5
  description: Highly available Prometheus setup with long term storage capabilities.
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - thanos=0.31.999

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - bash
      - go
      - curl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/thanos-io/thanos
      tag: v${{package.version}}
      expected-commit: 50c464132c265eef64254a9fd063b1e2419e09b7

  - runs: |
      # Fails to build on go1.21 without this. Remove in next release.
      # See https://github.com/thanos-io/thanos/pull/6609
      go get -u go4.org/intern@6c62f75575cbbc91d0d439652bef2613e7889238
      # Mitigate CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0

      go mod tidy
      make build

  - runs: |
      install -Dm755 .cache/go/bin/thanos "${{targets.destdir}}"/usr/bin/thanos

  - uses: strip

update:
  enabled: true
  github:
    identifier: thanos-io/thanos
    strip-prefix: v
    tag-filter: v0.31.
