package:
  name: trillian
  version: 1.5.2
  epoch: 5
  description: Merkle tree implementation used in Sigstore
  copyright:
    - license: Apache-2.0
  checks:
    disabled:
      - empty

environment:
  contents:
    packages:
      - build-base
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/google/trillian
      tag: v${{package.version}}
      expected-commit: 8ba85b59c6eca840b1b673b7afc6c9516329a690

  - runs: |
      # Mitigate CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy

subpackages:
  - name: ${{package.name}}-logserver
    pipeline:
      - uses: go/build
        with:
          modroot: .
          subpackage: "true"
          packages: ./cmd/trillian_log_server
          output: trillian_log_server
          ldflags: -w
      - uses: strip

  - name: ${{package.name}}-logsigner
    pipeline:
      - uses: go/build
        with:
          modroot: .
          subpackage: "true"
          packages: ./cmd/trillian_log_signer
          output: trillian_log_signer
          ldflags: -w
      - uses: strip

update:
  enabled: true
  github:
    identifier: google/trillian
    strip-prefix: v
