package:
  name: trust-dns
  version: 0.23.1
  epoch: 0
  description: ""
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - rust
      - libLLVM-15
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - openssl-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bluejekyll/trust-dns
      tag: v${{package.version}}
      expected-commit: 228210c36854a16a0d8fc59e7c77932b00a870d5

  - name: Configure and build
    runs: |
      cargo build --release -p trust-dns --all-features
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/trust-dns ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: bluejekyll/trust-dns
    strip-prefix: v
    tag-filter: v
