package:
  name: trust-manager
  version: 0.6.0
  epoch: 5
  description: trust-manager is an operator for distributing trust bundles across a Kubernetes cluster.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - wolfi-baselayout
      - busybox
      - build-base
      - go
      - ca-certificates-bundle

pipeline:
  # We can't use go/install because this requires specific ldflags to set the version
  - uses: git-checkout
    with:
      repository: https://github.com/cert-manager/trust-manager
      tag: v${{package.version}}
      expected-commit: 9bdf39df85ce523746aeedff0eacc70f887176c1
      destination: trust-manager

  - runs: |
      cd trust-manager

      # Mitigate CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy

      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      install -Dm755 ./bin/trust-manager ${{targets.destdir}}/usr/bin/trust-manager

  - uses: strip

update:
  enabled: true
  github:
    identifier: cert-manager/trust-manager
    strip-prefix: v
    use-tag: true
    tag-filter: v
