package:
  name: vault-1.13
  version: 1.13.8
  epoch: 4
  description: Tool for encryption as a service, secrets and privileged access management
  copyright:
    - license: MPL-2.0
  dependencies:
    provides:
      - vault=1.13.999 # This is because we had a 1.13.3 vault package, remove in 1.15+

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - libcap-utils
      - nodejs-16
      - py3-setuptools
      - python3
      - yarn

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hashicorp/vault
      tag: v${{package.version}}
      expected-commit: 4c785b0584b9165a9d4410f22c7491a4c8eec95f
      destination: vault

  - runs: |
      cd vault

      go get github.com/cloudflare/circl@v1.3.3
      # Mitigate CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy

      go generate $(go list ./... | grep -v /vendor/)

      # Build plugins
      grep "^[a-z].*plugin[:]" Makefile | cut -f1 -d: | while IFS= read -r plugin; do
        echo "--> Building $plugin"
        make "$plugin"
      done

      NODE_OPTIONS="--openssl-legacy-provider" make static-dist
      _gotags="vault ui"

      _go_ldflags="
      -s -w
      -X github.com/hashicorp/vault/sdk/version.Version=${{package.version}}
      -X github.com/hashicorp/vault/sdk/version.GitCommit=$(git rev-parse HEAD)
      -X github.com/hashicorp/vault/sdk/version.BuildDate=$(date ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")
      "

      CGO_ENABLED=0 go build -v -o bin/vault -ldflags "$_go_ldflags" -tags "$_gotags"

  - runs: |
      install -m644 -D "./vault.confd" "${{targets.destdir}}/etc/conf.d/vault"

      install -m755 -D ./vault/bin/vault "${{targets.destdir}}/usr/bin/vault"

      # Directory for config. Vault user needs write privileges
      install -m777 -d "${{targets.destdir}}/etc/vault"

      # Directory for logs. Vault user needs write privileges.
      install -m777 -d "${{targets.destdir}}/var/lib/vault"
      install -m777 -d "${{targets.destdir}}/var/log/vault"

  - uses: strip

subpackages:
  - name: "${{package.name}}-compat"
    description: "Container entrypoint script for vault and required dependencies"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/usr/bin"
          install -m755 ./docker-entrypoint.sh "${{targets.subpkgdir}}/usr/bin/docker-entrypoint.sh"

          # The upstream helm chart expects the entrypoint in /usr/local/bin
          mkdir -p "${{targets.subpkgdir}}/usr/local/bin"
          ln -s /usr/bin/docker-entrypoint.sh "${{targets.subpkgdir}}/usr/local/bin/docker-entrypoint.sh"
    dependencies:
      provides:
        - vault-entrypoint=1.13.999 # This is because we had a 1.13.3 vault package, remove in 1.15+
        - ${{package.name}}-entrypoint=1.13.999 # This was previously called vault-entrypoint, remove in 1.15+
      runtime:
        - dumb-init
        - busybox
        - su-exec
        - libcap-utils

update:
  enabled: true
  github:
    identifier: hashicorp/vault
    strip-prefix: v
    tag-filter: v1.13.
