package:
  name: vault-k8s
  version: 1.3.0 # When updating, make sure to check that the license is still MPL!
  epoch: 0
  description: Tool for encryption as a service, secrets and privileged access management
  copyright:
    - license: MPL-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hashicorp/vault-k8s
      tag: v${{package.version}}
      expected-commit: 1b1d69e438d54aa5442782a5ed66751877ca6d03
      destination: vault-k8s

  - runs: |
      cd vault-k8s
      # Our builtin LDFLAGS conflict with some makefile defined Go-specific ones.
      unset LDFLAGS

      # Mitigate GHSA-vvpx-j8f3-3w6h
      # Mitigate CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy
      make build GOARCH=$(go env GOARCH) VERSION=${{package.version}}

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      install -m755 -D vault-k8s/dist/vault-k8s "${{targets.destdir}}/usr/bin/"

  - uses: strip

update:
  enabled: true
  github:
    identifier: hashicorp/vault-k8s
    strip-prefix: v
    use-tag: true
