package:
  name: wasm-tools
  version: 1.0.47
  epoch: 0
  description: "Low level tooling for WebAssembly in Rust"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - rust
      - libLLVM-15
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bytecodealliance/wasm-tools
      tag: wasm-tools-${{package.version}}
      expected-commit: 722b5996669affa63876d557cb807c1e1df45380

  - name: Configure and build
    runs: |
      cargo build --release -vv
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/wasm-tools ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: bytecodealliance/wasm-tools
    strip-prefix: wasm-tools-
