package:
  name: weaviate
  version: 1.21.7
  epoch: 0
  description: Weaviate is an open source vector database that stores both objects and vectors, allowing for combining vector search with structured filtering with the fault-tolerance and scalability of a cloud-native database, all accessible through GraphQL, REST, and various language clients.
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/weaviate/weaviate
      tag: v${{package.version}}
      expected-commit: ffb9a28740ff8880f08866b52b1e589c0b9d60f9

  - runs: |
      mkdir -p ${{targets.destdir}}/bin
      GITHASH=$(git rev-parse --short HEAD)
      # Mitigate CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0
      go mod tidy
      go build \
        -ldflags '-w -extldflags "-static" -X github.com/weaviate/weaviate/usecases/config.GitHash='"$GITHASH"'' \
        -o ${{targets.destdir}}/bin/weaviate ./cmd/weaviate-server

  - uses: strip

update:
  enabled: true
  github:
    identifier: weaviate/weaviate
    strip-prefix: v
    tag-filter: v
    use-tag: true
