package:
  name: wolfictl
  version: 0.6.0
  epoch: 0
  description: Helper CLI for managing Wolfi
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/wolfi-dev/wolfictl
      tag: v${{package.version}}
      expected-commit: a5f566017bb1c4c574ea8cdbabe6c3cb733c939a
      destination: wolfictl

  - uses: go/build
    with:
      packages: .
      output: wolfictl
      modroot: wolfictl

update:
  enabled: true
  github:
    identifier: wolfi-dev/wolfictl
    strip-prefix: v
    use-tag: true
