package:
  name: xfsprogs
  version: 6.5.0
  epoch: 0
  description: XFS filesystem utilities
  copyright:
    - license: LGPL-2.1-or-later

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - util-linux-dev
      - attr-dev
      - inih-dev
      - linux-headers
      - userspace-rcu-dev
      - userspace-rcu-static
      - gettext-dev
      - file
      - readline-dev
      - libtool
      - bash

pipeline:
  - uses: fetch
    with:
      uri: https://mirrors.edge.kernel.org/pub/linux/utils/fs/xfs/xfsprogs/xfsprogs-${{package.version}}.tar.xz
      expected-sha512: 0a2db9c3df8209b2b6d264b7ef87f4c101f5129dfa14cb09159dbef181c09508fa8460eb1f4293300f24696ce236ca49065e47068cebdee00ee8ab9e2b75211c

  - uses: autoconf/configure
    with:
      opts: |
        --sbindir=/usr/sbin \
        --enable-gettext=no

  - uses: autoconf/make

  - runs: |
      make DIST_ROOT="${{targets.destdir}}" PKG_ROOT_SBIN_DIR="/usr/sbin" PKG_ROOT_LIB_DIR="/usr/lib64" install install-dev

      find ${{targets.destdir}} -name '*.la' -print -exec rm \{} \;

      chown -R root:root "${{targets.destdir}}"/*

  - uses: strip

subpackages:
  - name: xfsprogs-dev
    description: "headers for xfsprogs"
    pipeline:
      - uses: split/dev

  - name: xfsprogs-libs
    description: "libraries for xfsprogs"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib64
          mv "${{targets.destdir}}"/usr/lib64/lib*.so.* "${{targets.subpkgdir}}"/usr/lib64

  - name: xfsprogs-doc
    description: "xfsprogs manpages"
    pipeline:
      - uses: split/manpages

  - name: xfs-scrub
    description: "xfs-scrub attempts to check and repair all metadata in a mounted XFS filesystem"
    dependencies:
      runtime:
        - xfsprogs
        - python3
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/xfsprogs
          mv "${{targets.destdir}}"/usr/lib/xfsprogs/xfs_scrub* "${{targets.subpkgdir}}"/usr/lib/xfsprogs/

          mkdir -p "${{targets.subpkgdir}}"/usr/sbin
          mv "${{targets.destdir}}"/usr/sbin/xfs_scrub* "${{targets.subpkgdir}}"/usr/sbin/

update:
  enabled: true
  release-monitor:
    identifier: 5188
