package:
  name: yq
  version: 4.35.2
  epoch: 3
  description: "yq is a portable command-line YAML, JSON, XML, CSV and properties processor"
  copyright:
    - license: Apache License 2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/mikefarah/yq
      tag: v${{package.version}}
      expected-commit: a198f72367ce9da70b564a2cc25399de8e27bf37

  - uses: go/build
    with:
      packages: .
      output: yq
      # Mitigate CVE-2023-39325 and CVE-2023-3978
      deps: golang.org/x/net@v0.17.0

  - runs: |
      ${{targets.destdir}}/usr/bin/yq --version | grep "version v${{package.version}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: mikefarah/yq
    strip-prefix: v
