package:
  name: zstd
  version: 1.5.5
  epoch: 1
  description: "the Zstandard compression algorithm"
  copyright:
    - license: BSD-2-Clause AND GPL-2.0-only

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - grep

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/facebook/zstd/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: 98e9c3d949d1b924e28e01eccb7deed865eefebf25c2f21c702e5cd5b63b85e1

  - runs: |
      make -j$(nproc) CC=${{host.triplet.gnu}}-gcc

  - runs: |
      make install PREFIX="/usr" DESTDIR="${{targets.destdir}}"

  - uses: strip

subpackages:
  - name: "zstd-doc"
    description: "zstd documentation"
    pipeline:
      - uses: split/manpages
      - uses: split/infodir

  - name: "zstd-dev"
    description: "zstd development headers"
    pipeline:
      - uses: split/dev

  - name: "zstd-static"
    description: "zstd static libraries"
    pipeline:
      - uses: split/static

  - name: "libzstd1"
    description: "libzstd runtime libraries"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libzstd.so.* "${{targets.subpkgdir}}"/usr/lib/

update:
  enabled: true
  release-monitor:
    identifier: 12083
