name: Build Bitnami Compatibility Package

needs:
  packages:
    - git

inputs:
  image:
    description: |
      The bitnami image.
    required: true

  version-path:
    description: |
      The path to the root of the Dockerfile, relative to the image name.
    required: true

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bitnami/containers
      branch: main
      destination: bitnami
  - runs: |
      mkdir -p ${{targets.contextdir}}

      if [ -d "./bitnami/bitnami/${{inputs.image}}/${{inputs.version-path}}/prebuildfs" ]; then
        cp -rf ./bitnami/bitnami/${{inputs.image}}/${{inputs.version-path}}/prebuildfs/* ${{targets.contextdir}}/
      fi

      if [ -d "./bitnami/bitnami/${{inputs.image}}/${{inputs.version-path}}/rootfs" ]; then
        cp -rf ./bitnami/bitnami/${{inputs.image}}/${{inputs.version-path}}/rootfs/* ${{targets.contextdir}}/
      fi
